import type { NpcDialogueCatalog } from "./types";

// Sprint Living NPCs (MVP) — Borin, o Ferreiro: curto, grosso, engraçado
// sem querer. Nunca fala mais do que precisa.
export const BORIN_DIALOGUE: NpcDialogueCatalog = {
  boas_vindas: [
    "Entra. Não vou morder.",
    "Chegou na hora certa. Ou errada. Tanto faz.",
    "Bem-vindo à forja. Cuidado com as brasas.",
    "Mais um vivo. Bom sinal.",
    "Senta aí. Ou fica de pé. Não ligo.",
  ],
  primeiro_encontro: [
    "Nunca te vi por aqui. Bom trabalho continuar vivo até agora.",
    "Cara nova. Vamos ver quanto tempo dura.",
    "Primeira vez na forja? Não toca em nada quente.",
    "Você é novo. Isso explica a cara de perdido.",
    "Bem-vindo. Espero que dure mais que minhas últimas luvas.",
  ],
  novato: [
    "Ainda cheira a Capital em você.",
    "Relaxa. Todo mundo começa sem saber segurar uma espada direito.",
    "Vai por partes. Ninguém nasceu sabendo forjar nada.",
    "Suas mãos ainda tremem. Vai passar.",
    "Novato, hein. Já vi piores. Não muitos, mas já vi.",
  ],
  veterano: [
    "Você já não fica mais impressionado com nada, né.",
    "Olha essas mãos. Já pegaram em espada de verdade.",
    "Você voltou inteiro de novo. Impressionante ou sorte.",
    "Já não precisa de conselho meu. Só de equipamento.",
    "Veterano é aquele que ainda aparece depois de tudo que já viu.",
  ],
  nivel_alto: [
    "Cê tá forte. Não vou fingir que não notei.",
    "Tem gente que sobe de nível. Você sobe de má vontade em prestar atenção nisso.",
    "Não precisa mais de mim pra nada, né.",
    "Continua voltando aqui mesmo forte assim. Respeito isso.",
    "Poder não enferruja. Bom saber.",
  ],
  boss_derrotado: [
    "Ouvi dizer que você encarou um Boss. Ainda tá de uma peça, vejo.",
    "Boss derrotado. Não vou fazer festa, mas... bom trabalho.",
    "Voltou de um Boss e não trouxe nada quebrado pra eu consertar? Decepcionante.",
    "Isso aí conta história. Não vou contar, mas conta.",
    "Sobreviveu a um Boss. As luvas ainda estão inteiras?",
  ],
  sem_gold: [
    "Sem Gold de novo. Familiar.",
    "Não vim aqui pra financiar ninguém.",
    "Fiado, não. Aqui não é caridade.",
    "Volta quando tiver moeda. Ou um bom motivo.",
    "Tá liso. Todo mundo tá, em algum momento.",
  ],
  muito_gold: [
    "Cê tá rico de repente. Suspeito.",
    "Muito Gold pra alguém que ainda usa esse equipamento.",
    "Não vou perguntar de onde veio esse dinheiro todo.",
    "Rico assim e ainda aparece na forja de um ferreiro velho.",
    "Guarda esse dinheiro direito. Ou gasta comigo. Prefiro a segunda.",
  ],
  chovendo: [
    "Chuva enferruja tudo. Detesto.",
    "Dia de chuva é dia de martelo parado.",
    "Chovendo assim, nem os lobos saem da toca.",
    "Guarda o equipamento seco. Não repito isso duas vezes.",
    "Chuva boa é a que não entra na forja.",
  ],
  noite: [
    "Trabalho melhor de noite. Menos gente enchendo o saco.",
    "A forja não dorme. Eu também não, aparentemente.",
    "Noite é hora de martelo e silêncio.",
    "Se veio de noite, é sério ou é besteira. Geralmente besteira.",
    "Noite na Capital é mais honesta que o dia.",
  ],
  primeira_visita: [
    "Primeira vez aqui. Não quebra nada.",
    "Bem-vindo à forja. Regra única: não toca no que tá vermelho.",
    "Essa é sua primeira vez. Vou fingir que isso me importa.",
    "Olha em volta. Depois volta quando precisar de verdade.",
    "Primeira visita sempre é só curiosidade. Volta quando for necessidade.",
  ],
  visitas_repetidas: [
    "Você de novo.",
    "Voltou. Achei que tinha desistido de mim.",
    "Essa já é a quantas vezes essa semana?",
    "Já devia ter sua própria bigorna, do tanto que aparece.",
    "Sempre que penso que não vou te ver de novo, cá está você.",
  ],
  aleatorias: [
    "Martelo bom dura mais que amizade.",
    "Fogo não perdoa distração.",
    "Aço bom não precisa se explicar.",
    "Já quebrei mais ferramentas do que promessas. E olha que quebrei bastante promessa.",
    "Trabalho, durmo, repito. Vida simples.",
  ],
  humor: [
    "Cê já tentou consertar bota com martelo? Eu já. Não recomendo.",
    "Um dia vou aprender a cozinhar. Hoje não é esse dia.",
    "Minhas mãos são ferramentas. Minha cara, nem tanto.",
    "Já bati o dedo com martelo mais vezes do que consigo admitir.",
    "Se eu risse de tudo que faço de errado, riria o dia inteiro.",
  ],
  conselhos: [
    "Cuida do que usa. O resto se cuida sozinho.",
    "Equipamento ruim mata mais que monstro.",
    "Nunca economiza em bota. Você anda com os pés, não com a carteira.",
    "Aprende a afiar sua própria lâmina. Um dia eu não vou estar aqui.",
    "Antes de sair por aí, checa o equipamento duas vezes.",
  ],
  fofocas: [
    "Greta sabe de tudo. Não pergunta como.",
    "Ouvi dizer que a Talia vendeu a mesma espada três vezes. Acredito.",
    "Dorwin reclama de tudo. Até do próprio Gold.",
    "Alguém falou que o Kade treina sozinho de madrugada. Não duvido.",
    "Não repito fofoca. Mas essa era boa.",
    // Sprint Wolves Ecosystem (Phase I)
    "Um lobo já roeu o cabo de um martelo esquecido do lado de fora da forja. Não pergunta como sei.",
    "Não forjo armadilha pra lobo. Nunca fui esse tipo de ferreiro.",
    "Couro de Lobo Alfa é raro de achar sem rasgo. O bicho não se entrega fácil, nem morto.",
  ],
  comentarios_reino: [
    "Esse Reino se sustenta na teimosia de quem não desiste.",
    "Capital continua de pé. Isso já é uma vitória.",
    "Reino pequeno, problemas grandes. Sempre foi assim.",
    "As pessoas aqui trabalham demais e reclamam de menos do que deveriam.",
    "Esse Reino tem mais história do que aparenta.",
  ],
  comentarios_npcs: [
    "Dorwin conta moeda duas vezes. Eu só bato o martelo uma.",
    "A Miriam lê demais. Eu leio o suficiente pra saber o preço do ferro.",
    "O Roth desconfia até da própria sombra.",
    "A Elenya lidera bem. Melhor que eu lideraria, com certeza.",
    "O Yannick fica olhando bicho o dia inteiro. Cada um com sua forja.",
  ],
  raras: [
    "Uma vez forjei uma espada que quebrou na primeira batalha. Nunca mais falei sobre isso. Até agora.",
    "Tive um mestre antes de mim. Ele era pior ferreiro do que eu sou hoje.",
    "Já pensei em desistir disso tudo. Uma vez. Só uma.",
    "Guardo a primeira ferramenta que usei. Não pergunta onde.",
    "Nem tudo que sai daqui quebrado é falha minha. A maioria, sim, mas nem tudo.",
  ],
  extremamente_raras: [
    "Se um dia essa forja apagar de vez, quero que alguém continue acendendo ela.",
    "Tenho medo de uma coisa só: que ninguém mais precise de ferreiro um dia.",
    "Já fiquei em silêncio aqui dentro por horas. O fogo estava fraco demais pra alguém notar.",
    "Se eu sumir um dia, procura minhas ferramentas. O resto não importa.",
    "Às vezes penso que o barulho do martelo é a única coisa que me impede de pensar demais.",
  ],
};
