import type { NpcDialogueCatalog } from "./types";

// Sprint Living NPCs (MVP) — Kade, o Mestre da Arena: vive falando de
// treino, competição e disciplina. Tudo, pra ele, é uma questão de
// preparo.
export const KADE_DIALOGUE: NpcDialogueCatalog = {
  boas_vindas: [
    "Entra. Espero que tenha treinado hoje.",
    "Bem-vindo à Arena. Aqui só existe disciplina.",
    "Chegou. Bom. Sempre há espaço pra mais um que queira treinar.",
    "Bem-vindo. Cicatrizes contam mais histórias que troféus, lembre-se disso.",
    "Entra. Já treinei antes de você chegar. Sempre treino antes.",
  ],
  primeiro_encontro: [
    "Cara nova na Arena. Vamos ver do que você é feito.",
    "Nunca te vi treinar. Isso muda agora.",
    "Primeira vez aqui? Espero que não seja a última.",
    "Bem-vindo. Toda jornada começa com o primeiro treino.",
    "Você é novo. Isso não é desculpa pra não se esforçar.",
  ],
  novato: [
    "Novato. Treino compensa a falta de experiência, com o tempo.",
    "Todo campeão começou sem saber nada. Continue treinando.",
    "Disciplina supera talento no começo. Lembra disso.",
    "Você ainda tem muito a aprender. Isso é bom. Significa espaço pra crescer.",
    "Iniciante que treina toda semana chega mais longe que talento que não aparece.",
  ],
  veterano: [
    "Veterano. Já não precisa de motivação, só de manutenção.",
    "Você treinou bastante pra chegar até aqui. Continue.",
    "Experiência sem treino contínuo enferruja rápido.",
    "Você já provou seu valor. Não pare agora.",
    "Veterano de verdade é aquele que ainda aparece pra treinar.",
  ],
  nivel_alto: [
    "Poder sem disciplina é desperdício. O seu, felizmente, parece ter as duas coisas.",
    "Forte assim, você virou referência. Trate isso com seriedade.",
    "Nível alto exige treino ainda mais rigoroso, não menos.",
    "Você chegou longe. Isso não significa que pode parar de treinar.",
    "Poder desse tamanho merece um adversário à altura. Ainda estou esperando um.",
  ],
  boss_derrotado: [
    "Um Boss derrotado. Isso é treino valendo a pena.",
    "Vitória contra um Boss prova mais que qualquer treino na Arena.",
    "Você encarou algo grande e venceu. Isso é disciplina em ação.",
    "Cicatrizes de Boss valem mais que qualquer troféu daqui.",
    "Parabéns. Agora volta pra treinar antes que fique convencido demais.",
  ],
  sem_gold: [
    "Sem Gold não impede ninguém de treinar.",
    "Aqui não cobra pra suar. Só exige esforço.",
    "Dinheiro vai e vem. Disciplina fica.",
    "Sem moeda hoje, mas com disposição, espero.",
    "Bolso vazio não é desculpa pra pular treino.",
  ],
  muito_gold: [
    "Muito Gold não compra disciplina. Isso se conquista.",
    "Rico assim, espero que também seja forte.",
    "Dinheiro não substitui treino. Nunca substituiu.",
    "Gold em excesso é bom. Poder conquistado com esforço é melhor.",
    "Guarda esse dinheiro. Ou investe em treino, se quiser meu conselho.",
  ],
  chovendo: [
    "Chuva não cancela treino. Só molha o chão.",
    "Treinar na chuva separa quem é sério de quem não é.",
    "Dia de chuva é dia de testar sua determinação.",
    "A Arena continua aberta, chova o quanto for.",
    "Chuva é só mais um obstáculo. Treino é sobre superar obstáculos.",
  ],
  noite: [
    "Treino de madrugada. Ninguém questiona, ninguém atrapalha.",
    "A Arena vazia de noite é o melhor lugar pra pensar.",
    "Se veio treinar de noite, já tem minha admiração.",
    "Noite é quando eu treino sozinho. Sempre foi assim.",
    "Escuridão não desculpa preguiça.",
  ],
  primeira_visita: [
    "Primeira vez na Arena. Espero que não seja a última.",
    "Bem-vindo. Aqui você vai suar antes de aprender qualquer coisa.",
    "Você nunca treinou aqui. Isso muda hoje.",
    "Primeira visita é onde tudo começa. Aproveita.",
    "Entra. Vamos ver seu potencial de verdade.",
  ],
  visitas_repetidas: [
    "Você de novo. Isso é disciplina, ou eu não entendo mais nada.",
    "Voltou pra treinar. Exatamente como devia ser.",
    "Sua constância impressiona.",
    "Cada vez que aparece, fica um pouco mais forte. Continua assim.",
    "Voltar sempre pra treinar é o que separa quem cresce de quem estagna.",
  ],
  aleatorias: [
    "Cicatrizes contam mais histórias que troféus.",
    "Já vi incontáveis Bosses caírem. Lembro do nome de quem os derrotou.",
    "Treino todo dia. Até quando não quero.",
    "Disciplina é fazer o que precisa ser feito, mesmo sem vontade.",
    "Um bom adversário te ensina mais que dez vitórias fáceis.",
  ],
  humor: [
    "Já treinei tanto num dia que nem lembrava meu próprio nome depois.",
    "Uma vez desafiei minha própria sombra. Perdi. Não pergunta como.",
    "Treino também ajuda. Principalmente quando você acha que não precisa.",
    "Já caí de tanto treinar equilíbrio. A ironia não passou despercebida.",
    "Se disciplina fosse engraçada, eu seria o homem mais engraçado do Reino.",
  ],
  conselhos: [
    "Treina todo dia, mesmo que pouco.",
    "Nunca subestima um adversário calmo.",
    "Descanso faz parte do treino. Não é preguiça, é estratégia.",
    "Foco vale mais que força bruta.",
    "Antes de correr atrás de um Boss, aprenda a se defender de um lobo.",
  ],
  fofocas: [
    "Ouvi dizer que alguém enfrentou um Boss usando Luvas Rasgadas. Respeito a ousadia.",
    "Dizem que o Borin nunca perde uma discussão sobre ferro. Nunca testei.",
    "A Greta sabe de tudo que acontece na Arena antes de mim, às vezes.",
    "Escutei que a Talia tentou me vender um equipamento de treino inútil. Não caí.",
    "Não repito fofoca fora da Arena. Aqui dentro, tudo bem.",
  ],
  comentarios_reino: [
    "Esse Reino precisa de mais gente disposta a treinar de verdade.",
    "Capital forte é Capital que treina, não só que celebra vitórias.",
    "Vejo potencial nesse Reino. Falta só disciplina coletiva.",
    "Esse lugar produz bons aventureiros. Poderia produzir ainda melhores.",
    "O Reino respeita quem se esforça. Isso eu aprovo.",
  ],
  comentarios_npcs: [
    "O Borin entende de ferramenta como eu entendo de treino.",
    "A Elenya lidera com disciplina. Reconheço isso nela.",
    "O Roth tem a postura de quem treinou a vida toda. Desconfio que treinou mesmo.",
    "A Miriam nunca pisou aqui, que eu saiba. Cada um tem seu campo de batalha.",
    "O Yannick observa tudo como se fosse estudar meu treino. Talvez seja.",
  ],
  raras: [
    "Já perdi uma luta importante por excesso de confiança. Nunca mais repeti o erro.",
    "Tive um mestre que me ensinou tudo que sei. Ele nunca aceitou nenhum crédito por isso.",
    "Uma vez pensei em desistir da Arena. Foi um treino ruim que me fez ficar.",
    "Guardo a memória de cada Boss que vi cair. Todos eles.",
    "Já treinei até sangrar. Não recomendo, mas não me arrependo.",
  ],
  extremamente_raras: [
    "Tenho medo de um dia não ter mais ninguém disposto a treinar de verdade.",
    "Se eu cair um dia, quero que seja treinando, não descansando.",
    "Já chorei depois de uma vitória difícil. Ninguém viu. Prefiro assim.",
    "Se algo me acontecer, quero que a Arena continue de portas abertas pra qualquer um disposto a suar.",
    "Treino desde sempre porque tenho medo do dia em que não for mais forte o bastante pra proteger esse Reino.",
  ],
};
