import type { NpcDialogueCatalog } from "./types";

// Sprint Living NPCs (MVP) — Zoltar, o Alquimista: ligeiramente maluco,
// fala coisas estranhas, às vezes parece prever o futuro. Ninguém sabe
// se ele está certo.
export const ZOLTAR_DIALOGUE: NpcDialogueCatalog = {
  boas_vindas: [
    "Ah... eu sabia que você viria. Bem, eu suspeitava.",
    "Entra, entra. Os frascos gostam de visita.",
    "Bem-vindo. Ou já esteve aqui antes? O tempo é estranho comigo.",
    "Senti sua chegada três borbulhas atrás.",
    "Entra devagar. Alguma coisa aqui reage a passos apressados.",
  ],
  primeiro_encontro: [
    "Você é novo. Ou eu esqueci de você. As duas coisas acontecem.",
    "Nunca te vi. Mas os frascos pareciam esperar alguém.",
    "Primeira vez? Interessante. Eu quase nunca erro sobre isso. Quase.",
    "Cara nova. O caldeirão borbulhou diferente quando você entrou.",
    "Bem-vindo. Não vou perguntar seu nome. Prefiro adivinhar.",
  ],
  novato: [
    "Novato. Os iniciantes sempre cheiram a coragem e pouco mais.",
    "Você ainda não sabe o que não sabe. Isso é raro de admitir.",
    "Vejo pouca experiência em você. E um pouco de sorte. Vamos ver qual dura mais.",
    "Novo por aqui. As coisas vão ficar mais estranhas, prometo.",
    "Iniciante. Toma cuidado com o que cheira doce demais.",
  ],
  veterano: [
    "Você já não se assusta mais com meus frascos. Isso me preocupa um pouco.",
    "Veterano. Vejo cicatrizes que os frascos não explicam.",
    "Você mudou desde a última vez. Ou eu que mudei de percepção.",
    "Já não é mais surpresa pra mim. Isso é raro de acontecer.",
    "Experiente o bastante pra desconfiar de tudo aqui. Bom instinto.",
  ],
  nivel_alto: [
    "Seu poder mudou de cor. Sim, eu vejo cor onde não deveria haver.",
    "Forte. Os frascos tremeram um pouco quando você entrou.",
    "Você cresceu além do que os números mostram, eu acho.",
    "Nível alto. Ou eu sou eu que estou ficando mais velho e tudo parece mais forte.",
    "Poder desse tamanho merece um frasco à parte. Não tenho um pronto ainda.",
  ],
  boss_derrotado: [
    "Eu sabia. Ou pelo menos suspeitava fortemente.",
    "Um Boss caiu. Senti o ar mudar antes de ouvir a notícia.",
    "Derrotou um Boss. Isso explica o cheiro de ozônio em você.",
    "Vitória contra um Boss. Os frascos comemoraram borbulhando mais forte.",
    "Você sobreviveu a algo grande. Os pequenos frascos sentiram primeiro.",
  ],
  sem_gold: [
    "Sem Gold. Previsível. Eu já sabia, aliás.",
    "Bolso vazio. Os frascos também estão vazios hoje. Coincidência? Duvido.",
    "Sem moeda agora. Vai passar. Ou não. Difícil dizer com certeza absoluta.",
    "Ah, sem Gold. Isso eu vi chegando de longe.",
    "Sem dinheiro. Os ingredientes também não crescem em árvore. Bem, alguns crescem.",
  ],
  muito_gold: [
    "Muito Gold em você agora. Interessante, eu não previ isso.",
    "Rico de repente. Os frascos ficaram curiosos.",
    "Gold em excesso atrai coisas estranhas. Cuidado.",
    "Você tem moedas demais pra alguém tão desconfiado quanto eu esperava.",
    "Dinheiro assim muda o cheiro de uma pessoa. Achei que era invenção minha até agora.",
  ],
  chovendo: [
    "A chuva conversa com meus frascos. Eu só traduzo.",
    "Dia de chuva, dia de reações estranhas. Sempre foi assim.",
    "Chovendo. Os ingredientes ficam mais falantes nesses dias.",
    "Gosto de chuva. Os frascos concordam comigo, aparentemente.",
    "Chuva lá fora, mistério aqui dentro. Combinação perfeita.",
  ],
  noite: [
    "A noite é quando os frascos falam a verdade.",
    "De noite eu vejo coisas que de dia finjo não ver.",
    "Noite boa pra experimentos. Ninguém pergunta demais.",
    "O silêncio da noite deixa os borbulhos mais claros.",
    "Prefiro trabalhar de noite. O dia distrai demais.",
  ],
  primeira_visita: [
    "Primeira vez aqui. Eu já sabia que isso ia acontecer hoje.",
    "Bem-vindo pela primeira vez. Os frascos estavam ansiosos, juro.",
    "Você nunca esteve aqui. Interessante, eu sentia sua falta sem te conhecer.",
    "Primeira visita. Cuidado onde pisa, alguns frutos rolaram ontem.",
    "Entra devagar. É sua primeira vez, e a última impressão importa mais que a primeira, acho eu.",
  ],
  visitas_repetidas: [
    "Você de novo. Eu sabia que voltaria nesse exato momento.",
    "Voltou. Os frascos já estavam preparados, de alguma forma.",
    "Você aparece sempre que algo estranho está prestes a acontecer. Coincidência, garanto.",
    "Já é rotina sua vinda aqui. Rotina é uma palavra estranha pra mim.",
    "De novo por aqui. Bom. Ou ruim. O tempo dirá. Ele sempre diz, eventualmente.",
  ],
  aleatorias: [
    "Já vi o futuro num reflexo de poção uma vez. Ou era só vapor.",
    "Ninguém sabe de onde eu vim. Eu também não tenho certeza.",
    "Os frascos nunca param de borbulhar. Nem eu sei por quê.",
    "Uma vez misturei duas coisas que não deveriam se misturar. Ainda estou aqui, então deu certo. Ou quase.",
    "O tempo é só uma sugestão, na minha experiência.",
  ],
  humor: [
    "Já tentei fazer poção de sono. Dormi três dias. Funcionou bem demais.",
    "Meu caldeirão explodiu uma vez só porque eu espirrei.",
    "As pessoas acham que eu sei tudo. Eu só finjo bem.",
    "Já confundi ingrediente de poção com o jantar. Foi uma noite interessante.",
    "Previ que ia chover. Estava certo. Também previ que ia nevar no mesmo dia. Errei feio.",
  ],
  conselhos: [
    "Nunca cheira algo que borbulha sozinho.",
    "Confia no seu instinto, mesmo quando ele parece maluco. Principalmente quando parece maluco.",
    "Guarda um pouco de tudo. Nunca sabe quando vai precisar.",
    "Não ignora os sinais pequenos. Eles avisam antes dos grandes.",
    "Se algo parece bom demais pra ser verdade, prova um pouquinho só. Nunca tudo de uma vez.",
  ],
  fofocas: [
    "Ouvi dizer que a Talia vendeu a mesma espada três vezes. Eu já sabia disso antes de ouvir, aliás.",
    "Dizem que o Borin fala sozinho na forja. Eu falo sozinho aqui também. Não julgo.",
    "A Greta sabe de tudo. Eu sei de quase tudo. A diferença é pequena.",
    "O Dorwin não gasta nem em ingredientes básicos. Isso eu não previ, mas não me surpreende.",
    "Escutei um rumor sobre mim mesmo outro dia. Nem tudo era mentira.",
  ],
  comentarios_reino: [
    "Esse Reino tem uma energia estranha. Boa estranha, acho eu.",
    "Sinto que esse lugar guarda mais segredos do que mostra.",
    "O Reino cresce. Os frascos sentem isso antes de qualquer relatório.",
    "Tem algo se formando nesse Reino. Não sei o quê. Ainda.",
    "Gosto daqui. Os ingredientes locais são generosos.",
  ],
  comentarios_npcs: [
    "O Borin é sólido como o próprio ferro que forja.",
    "A Talia fala tanto que às vezes eu paro de tentar prever o que ela vai dizer.",
    "A Elenya tem uma presença que os frascos respeitam.",
    "O Yannick entenderia meus experimentos melhor que ninguém. Um dia eu chamo ele aqui.",
    "A Greta escuta mais do que fala. Admiro isso.",
  ],
  raras: [
    "Uma vez previ minha própria queda. Literalmente. Escorreguei três dias depois.",
    "Tive um mestre. Ele desapareceu numa explosão de cor. Espero que tenha sido de propósito.",
    "Guardo uma poção que nunca tomei coragem de testar.",
    "Já vi algo no fundo de um caldeirão que prefiro não descrever.",
    "Às vezes acerto o futuro só porque acho que ele me escuta.",
  ],
  extremamente_raras: [
    "Tenho medo de um dia prever algo que eu não queira ver acontecer.",
    "Não sei se estou ficando mais sábio ou só mais estranho. As duas coisas parecem a mesma, ultimamente.",
    "Se um dia eu sumir no meio de uma explosão, saibam que era um experimento, não um acidente. Provavelmente.",
    "Às vezes tenho medo de que ninguém acredite em mim quando eu realmente acertar algo importante.",
    "Se esse caldeirão parar de borbulhar um dia, é porque algo mudou de verdade nesse mundo.",
  ],
};
