// Sprint Bestiary System — infraestrutura do Bestiário, reutilizando a
// mesma arquitetura da Biblioteca (catálogo estático, sem backend, sem
// banco, sem escrita). Puramente apresentação: nenhuma criatura aqui é
// Lore definitiva — cada uma é só um placeholder, pronto para receber
// texto real numa Sprint futura sem precisar mudar esta estrutura.
import { REGIONS } from "./regions";

export type CreatureType =
  | "besta"
  | "morto-vivo"
  | "elemental"
  | "humanoide"
  | "dragao"
  | "espirito"
  | "aberracao"
  | "construto"
  | "mamifero"
  | "inseto";

export interface CreatureTypeDefinition {
  slug: CreatureType;
  label: string;
  icon: string;
}

// Etapa "Categorias" — Sprint Creature Expansion (Phase I) adicionou
// "mamifero"/"inseto" às 8 categorias originais (pedidas explicitamente
// no catálogo expandido) — mesma estrutura de sempre, só duas entradas
// a mais, nenhuma mudança de mecânica (CreatureType nunca é lido por
// Combat/Boss, é só rótulo/filtro do Bestiário).
export const CREATURE_TYPES: CreatureTypeDefinition[] = [
  { slug: "besta", label: "Besta", icon: "🐺" },
  { slug: "morto-vivo", label: "Morto-vivo", icon: "💀" },
  { slug: "elemental", label: "Elemental", icon: "🔥" },
  { slug: "humanoide", label: "Humanoide", icon: "🗡️" },
  { slug: "dragao", label: "Dragão", icon: "🐉" },
  { slug: "espirito", label: "Espírito", icon: "👻" },
  { slug: "aberracao", label: "Aberração", icon: "👁️" },
  { slug: "construto", label: "Constructo", icon: "⚙️" },
  { slug: "mamifero", label: "Mamífero", icon: "🦊" },
  { slug: "inseto", label: "Inseto", icon: "🐝" },
];

export type DangerLevel = "baixa" | "media" | "alta" | "letal";

export const DANGER_LABEL: Record<DangerLevel, string> = {
  baixa: "Baixa",
  media: "Média",
  alta: "Alta",
  letal: "Letal",
};

// Sprint Creature Expansion (Phase I) — eixo novo, independente de
// dangerLevel (perigo em combate) e status (progresso de descoberta):
// o quão raro é encontrar a criatura. Puramente informativo/filtro do
// Bestiário, igual aos outros dois eixos — nenhuma regra de Combat/Drop
// real lê este campo.
export type CreatureRarity = "comum" | "incomum" | "raro" | "muito-raro" | "lendaria";

export const RARITY_LABEL: Record<CreatureRarity, string> = {
  comum: "Comum",
  incomum: "Incomum",
  raro: "Raro",
  "muito-raro": "Muito Raro",
  lendaria: "Lendária",
};

// Etapa "Locked / Seen / Studied" — só um estado aceito pela interface,
// igual à Biblioteca: nenhuma lógica de desbloqueio real ainda.
export type CreatureStatus = "bloqueado" | "visto" | "estudado";

export interface CreatureDefinition {
  id: string;
  name: string;
  type: CreatureType;
  habitat: string;
  regionId: string;
  dangerLevel: DangerLevel;
  icon: string;
  description: string;
  // Markdown simples (mesmo `renderMarkdownLite` da Biblioteca): só
  // **negrito**, *itálico* e parágrafos. Nada além disso nesta Sprint.
  pages: string[];
  locked: boolean;
  unlockCondition: string;
  status: CreatureStatus;
  // Sprint Creature Expansion (Phase I) — opcionais para não exigir
  // alteração das 5 criaturas já existentes acima (nenhuma foi tocada).
  // rarity: eixo de raridade de encontro (não confundir com dangerLevel).
  // suggestedLevel: nível sugerido pra encontrar a criatura, só leitura,
  // nenhuma regra de Encounter/Expedition consome isso ainda.
  rarity?: CreatureRarity;
  suggestedLevel?: number;
  // Sprint Content Connections (Phase I) — nenhum catálogo novo: só
  // referências (por slug/id) a conteúdo que já existe em outros
  // catálogos (itens, NPCs, rumores da Taverna, Histórias dos
  // Viajantes, Livraria). `regionId` acima já cobre a ligação de
  // região — não duplicado aqui. Todos os campos são opcionais e só
  // preenchidos quando existe uma correspondência real verificada
  // (nenhum item/rumor/história foi inventado para caber aqui).
  connections?: CreatureConnections;
}

export interface CreatureConnections {
  itemSlug?: string;
  npcKey?: string;
  npcNote?: string;
  rumor?: string;
  travellerStoryId?: string;
  bookId?: string;
}

export function getRegionName(regionId: string): string {
  return REGIONS.find((region) => region.id === regionId)?.name ?? regionId;
}

const PLACEHOLDER_PAGES = [
  "**Esta criatura ainda está sendo estudada.**\n\nOs eruditos da Capital continuam reunindo relatos de quem a encontrou.",
  "*Registro em desenvolvimento...*\n\nVolte ao Bestiário em outra ocasião.",
  "**Fim do registro conhecido.**\n\nO restante do comportamento desta criatura ainda não foi documentado.",
];

// Etapa "Dados" — 5 criaturas, só texto placeholder, nenhuma Lore
// definitiva. Tipos/regiões/periculosidades variados só para provar que
// os filtros funcionam.
export const CREATURES: CreatureDefinition[] = [
  {
    id: "lobos-cinzentos",
    name: "Lobos Cinzentos",
    type: "besta",
    habitat: "Florestas densas e sombrias",
    regionId: "bosque-sussurrante",
    dangerLevel: "baixa",
    icon: "🐺",
    description: "Criatura em estudo...",
    pages: PLACEHOLDER_PAGES,
    locked: false,
    unlockCondition: "Disponível desde o início",
    status: "estudado",
    connections: {
      itemSlug: "colar-dentes-lobo",
      npcKey: "ferreiro",
      npcNote: "Borin comenta que couro de lobo forte é raro de achar sem rasgos.",
      travellerStoryId: "lobo-de-olhos-claros",
      bookId: "bestiario-das-terras-selvagens",
    },
  },
  {
    id: "espectros-da-neblina",
    name: "Espectros da Neblina",
    type: "espirito",
    habitat: "Pântanos e ruínas alagadas",
    regionId: "pantano-podre",
    dangerLevel: "media",
    icon: "👻",
    description: "Criatura em estudo...",
    pages: PLACEHOLDER_PAGES,
    locked: false,
    unlockCondition: "Disponível desde o início",
    status: "visto",
    connections: {
      npcKey: "alquimista",
      npcNote: "Zoltar acredita que a neblina do pântano carrega mais do que só água.",
      rumor: "Um viajante jura ter visto luzes no Pântano Podre à noite.",
      travellerStoryId: "criatura-do-pantano-sem-nome",
    },
  },
  {
    id: "golens-de-pedra-antiga",
    name: "Golens de Pedra Antiga",
    type: "construto",
    habitat: "Galerias e minas abandonadas",
    regionId: "minas-abandonadas",
    dangerLevel: "alta",
    icon: "⚙️",
    description: "Criatura em estudo...",
    pages: PLACEHOLDER_PAGES,
    locked: false,
    unlockCondition: "Disponível desde o início",
    status: "visto",
    connections: {
      itemSlug: "lamina-forjada-minas-abandonadas",
      npcKey: "ferreiro",
      npcNote: "Borin estuda o mecanismo interno sempre que encontra um fragmento.",
    },
  },
  {
    id: "serpente-das-areias-de-vidro",
    name: "Serpente das Areias de Vidro",
    type: "aberracao",
    habitat: "Dunas vítreas e cegantes",
    regionId: "deserto-de-vidro",
    dangerLevel: "alta",
    icon: "👁️",
    description: "Criatura em estudo...",
    pages: PLACEHOLDER_PAGES,
    locked: true,
    unlockCondition: "Desconhecida",
    status: "bloqueado",
    connections: {
      itemSlug: "foice-deserto-vidro",
      npcKey: "alquimista",
      npcNote: "Zoltar tem uma teoria inteira sobre o veneno dela, nunca publicada.",
      rumor: "Dizem que o Deserto de Vidro engoliu mais uma bota essa semana.",
      travellerStoryId: "serpente-que-fala-baixo",
    },
  },
  {
    id: "o-sussurro-sem-nome",
    name: "O Sussurro Sem Nome",
    type: "aberracao",
    habitat: "Salões esquecidos da fortaleza",
    regionId: "fortaleza-sombria",
    dangerLevel: "letal",
    icon: "🔮",
    description: "Criatura em estudo...",
    pages: PLACEHOLDER_PAGES,
    locked: true,
    unlockCondition: "Desconhecida",
    status: "bloqueado",
    connections: {
      itemSlug: "lanca-fortaleza-sombria",
      npcKey: "alquimista",
      npcNote: "Zoltar se recusa terminantemente a comentar sobre esse.",
      rumor: "Ouviram cantoria vindo da Fortaleza Sombria. Ninguém foi conferir.",
      bookId: "misterios-da-fortaleza-sombria",
    },
  },

  // ============================================================
  // Sprint Creature Expansion — Phase I — 120 criaturas novas,
  // expandindo o catálogo já existente acima (nenhuma das 5 originais
  // foi tocada). Cada `pages` tem 3 entradas: pequena história,
  // curiosidade, e "drops futuros" (só texto de lore — nenhum drop real
  // implementado, nenhuma tabela, nenhuma regra de Combat/Encounter lê
  // isso). `rarity`/`suggestedLevel` são novos, opcionais, só leitura.
  // ============================================================

  // ---- Mamíferos (12): 4 comum · 3 incomum · 3 raro · 1 muito-raro · 1 lendária ----
  { id: "raposa-do-trigo", name: "Raposa-do-Trigo", type: "mamifero", rarity: "comum", suggestedLevel: 2, habitat: "Campos abertos e bordas de plantação", regionId: "planicie-dourada", dangerLevel: "baixa", icon: "🦊", description: "Rouba ovos de galinheiro sempre que pode.", pages: ["Aprendeu a abrir cercas simples observando fazendeiros descuidados.", "Alguns fazendeiros deixam um ovo de propósito, só pra ela ir embora satisfeita.", "Possíveis drops (lore, não implementado): Pele Alaranjada, Cauda Fofa, Dente Pequeno."], locked: false, unlockCondition: "Disponível desde o início", status: "visto" },
  { id: "javali-das-colinas", name: "Javali das Colinas", type: "mamifero", rarity: "comum", suggestedLevel: 3, habitat: "Encostas secas e trilhas estreitas", regionId: "colinas-aridas", dangerLevel: "media", icon: "🐗", description: "Destrói plantações inteiras numa única noite.", pages: ["Vive em bandos pequenos e defende o território com violência surpreendente.", "O Ferreiro Borin jura que um já derrubou uma cerca de ferro.", "Possíveis drops (lore, não implementado): Presa Curva, Couro Grosso, Casco Rachado."], locked: false, unlockCondition: "Disponível desde o início", status: "estudado", connections: { npcKey: "ferreiro", npcNote: "Borin jura que um javali já derrubou uma cerca de ferro inteira." } },
  { id: "esquilo-do-bosque", name: "Esquilo do Bosque", type: "mamifero", rarity: "comum", suggestedLevel: 1, habitat: "Copas altas e troncos ocos", regionId: "bosque-sussurrante", dangerLevel: "baixa", icon: "🐿️", description: "Rouba comida de qualquer mochila aberta.", pages: ["Enterra sementes e esquece a maioria, plantando metade da floresta sem querer.", "Idris jura que um já roubou uma moeda de dentro da bota dele.", "Possíveis drops (lore, não implementado): Pelagem Macia, Cauda Peluda, Semente Roubada."], locked: false, unlockCondition: "Disponível desde o início", status: "visto" },
  { id: "cabra-das-rochas", name: "Cabra das Rochas", type: "mamifero", rarity: "comum", suggestedLevel: 2, habitat: "Encostas íngremes e platôs altos", regionId: "colinas-aridas", dangerLevel: "baixa", icon: "🐐", description: "Escala paredes que nenhum humano tentaria.", pages: ["Vive em famílias pequenas, sempre no ponto mais alto disponível.", "Roth garante que uma já observou a Guarda do alto da muralha, por dias.", "Possíveis drops (lore, não implementado): Chifre Curvo, Pelo Áspero, Casco Firme."], locked: false, unlockCondition: "Disponível desde o início", status: "estudado" },
  { id: "doninha-do-celeiro", name: "Doninha do Celeiro", type: "mamifero", rarity: "incomum", suggestedLevel: 4, habitat: "Celeiros e depósitos de grão", regionId: "planicie-dourada", dangerLevel: "media", icon: "🐾", description: "Rouba ovos e foge antes de qualquer reação.", pages: ["Vive perto de celeiros, sempre um passo à frente de quem tenta pegá-la.", "Um fazendeiro jura que perdeu uma dúzia de ovos pra mesma doninha, num único mês.", "Possíveis drops (lore, não implementado): Pelagem Fina, Garra Curta, Cauda Listrada."], locked: false, unlockCondition: "Disponível desde o início", status: "visto" },
  { id: "texugo-teimoso", name: "Texugo Teimoso", type: "mamifero", rarity: "incomum", suggestedLevel: 5, habitat: "Tocas profundas perto de água parada", regionId: "pantano-podre", dangerLevel: "media", icon: "🦡", description: "Não recua de ninguém, nem de coisas maiores que ele.", pages: ["Cava tocas profundas e defende cada centímetro delas.", "Há uma aposta antiga na Taverna sobre quem consegue passar por um sem ser mordido.", "Possíveis drops (lore, não implementado): Garra Curta, Pelagem Escura, Presa Pequena."], locked: false, unlockCondition: "Disponível desde o início", status: "estudado", connections: { npcKey: "taverneira", npcNote: "Greta é quem toma conta da aposta antiga sobre o texugo." } },
  { id: "urso-das-minas", name: "Urso das Minas", type: "mamifero", rarity: "incomum", suggestedLevel: 6, habitat: "Galerias abandonadas e entradas escuras", regionId: "minas-abandonadas", dangerLevel: "alta", icon: "🐻", description: "Vive perto de galerias abandonadas, longe de qualquer trilha.", pages: ["Adaptou-se ao escuro das minas melhor que qualquer outro animal da região.", "Mineiros deixam comida na entrada só pra ele não entrar mais fundo.", "Possíveis drops (lore, não implementado): Garra Grossa, Pelagem Densa, Presa Longa."], locked: false, unlockCondition: "Disponível desde o início", status: "visto", connections: { itemSlug: "botas-forjadas-minas-abandonadas", npcKey: "ferreiro", npcNote: "Borin diz que o metal das Minas Abandonadas nunca esquenta de verdade — nem perto de um urso irritado." } },
  { id: "lince-do-deserto-de-vidro", name: "Lince do Deserto de Vidro", type: "mamifero", rarity: "raro", suggestedLevel: 9, habitat: "Dunas vítreas ao entardecer", regionId: "deserto-de-vidro", dangerLevel: "alta", icon: "🐆", description: "Caça sozinho e nunca deixa rastro na areia vitrificada.", pages: ["Poucos o veem duas vezes — a maioria só vê o brilho dos olhos à noite.", "Alguns caçadores duvidam que ele exista de verdade.", "Possíveis drops (lore, não implementado): Pelagem Reluzente, Garra de Vidro, Olho Claro."], locked: false, unlockCondition: "Disponível desde o início", status: "estudado", connections: { itemSlug: "botas-cacador-feras", npcKey: "erudito", npcNote: "Yannick duvida que o lince exista de verdade — mas guarda as marcas de garra como prova." } },
  { id: "alce-dos-picos", name: "Alce dos Picos", type: "mamifero", rarity: "raro", suggestedLevel: 10, habitat: "Vales altos entre a neve", regionId: "picos-congelados", dangerLevel: "media", icon: "🦌", description: "Migra em rotas que ninguém conseguiu mapear por completo.", pages: ["Aparece só em certas épocas do ano, e some por meses.", "Roth garante que um já parou o tráfego inteiro do Portão Norte por uma tarde.", "Possíveis drops (lore, não implementado): Chifre Congelado, Pelagem Grossa, Casco Duro."], locked: false, unlockCondition: "Disponível desde o início", status: "visto", connections: { itemSlug: "elmo-picos-congelados", npcKey: "guarda", npcNote: "Roth garante que um alce já parou o tráfego inteiro do Portão Norte por uma tarde." } },
  { id: "morcego-das-ruinas", name: "Morcego das Ruínas", type: "mamifero", rarity: "raro", suggestedLevel: 11, habitat: "Câmaras profundas sem luz", regionId: "ruinas-esquecidas", dangerLevel: "media", icon: "🦇", description: "Vive nas câmaras mais profundas, longe de qualquer luz.", pages: ["Guia-se por ecos entre paredes que ninguém mais consegue interpretar.", "Alaric acredita que eles vivem ali há mais tempo que as próprias Ruínas.", "Possíveis drops (lore, não implementado): Asa Fina, Presa Curva, Pelagem Escura."], locked: false, unlockCondition: "Disponível desde o início", status: "estudado" },
  { id: "urso-fantasma-da-fortaleza", name: "Urso-Fantasma da Fortaleza", type: "mamifero", rarity: "muito-raro", suggestedLevel: 15, habitat: "Corredores internos da fortaleza", regionId: "fortaleza-sombria", dangerLevel: "letal", icon: "🐻‍❄️", description: "Raramente ataca — na maioria das vezes, só observa de longe.", pages: ["Ninguém sabe explicar como um urso comum sobreviveria tanto tempo ali dentro.", "Alguns juram que ele é branco só à noite.", "Possíveis drops (lore, não implementado): Pelagem Pálida, Garra Imensa, Presa Gasta."], locked: true, unlockCondition: "Desconhecida", status: "bloqueado" },
  { id: "cervo-de-chifres-torcidos-bestiario", name: "O Cervo de Chifres Torcidos", type: "mamifero", rarity: "lendaria", suggestedLevel: 20, habitat: "Trecho único de floresta densa", regionId: "bosque-sussurrante", dangerLevel: "alta", icon: "🦌", description: "Foi visto três vezes em uma década, sempre no mesmo trecho de floresta.", pages: ["Alguns caçadores dedicam a vida inteira só pra vê-lo de novo.", "Yannick tem um caderno inteiro dedicado só a relatos sobre ele.", "Possíveis drops (lore, não implementado): Galhada Torcida, Pelagem Prateada, Casco Antigo."], locked: true, unlockCondition: "Desconhecida", status: "bloqueado", connections: { npcKey: "erudito", npcNote: "Yannick tem um caderno inteiro dedicado só a relatos sobre este cervo.", travellerStoryId: "cervo-de-chifres-torcidos", bookId: "bestiario-das-terras-selvagens" } },

  // ---- Insetos (12): 4 comum · 3 incomum · 3 raro · 1 muito-raro · 1 lendária ----
  { id: "vespa-da-colheita", name: "Vespa da Colheita", type: "inseto", rarity: "comum", suggestedLevel: 1, habitat: "Favos entre os trigais", regionId: "planicie-dourada", dangerLevel: "baixa", icon: "🐝", description: "Ataca quem se aproxima demais dos favos.", pages: ["Constrói ninhos enormes entre os trigais, todo verão.", "Talia vende mel dela na feira, mas nunca conta de onde tira.", "Possíveis drops (lore, não implementado): Ferrão Fino, Asa Transparente, Favo Pequeno."], locked: false, unlockCondition: "Disponível desde o início", status: "visto" },
  { id: "besouro-de-casco-duro", name: "Besouro de Casco Duro", type: "inseto", rarity: "comum", suggestedLevel: 1, habitat: "Terreno pedregoso e seco", regionId: "colinas-aridas", dangerLevel: "baixa", icon: "🪲", description: "Rola pedrinhas maiores que o próprio corpo.", pages: ["Ninguém sabe exatamente por quê ele faz isso.", "Crianças da Capital colecionam os cascos vazios que ele deixa para trás.", "Possíveis drops (lore, não implementado): Casco Reluzente, Perna Fina, Antena Curta."], locked: false, unlockCondition: "Disponível desde o início", status: "estudado" },
  { id: "formiga-de-fogo-da-planicie", name: "Formiga-de-Fogo da Planície", type: "inseto", rarity: "comum", suggestedLevel: 2, habitat: "Formigueiros na terra batida", regionId: "planicie-dourada", dangerLevel: "media", icon: "🐜", description: "Defende o formigueiro com uma agressividade fora do comum.", pages: ["Vive em colônias enormes, organizadas com precisão incomum.", "Um fazendeiro jura que elas reconstroem o formigueiro do mesmo jeito toda vez que é destruído.", "Possíveis drops (lore, não implementado): Mandíbula Pequena, Casco Avermelhado, Ferrão Ardido."], locked: false, unlockCondition: "Disponível desde o início", status: "visto" },
  { id: "grilo-da-taverna", name: "Grilo da Taverna", type: "inseto", rarity: "comum", suggestedLevel: 1, habitat: "Frestas perto de luz acesa", regionId: "porto-do-amanhecer", dangerLevel: "baixa", icon: "🦗", description: "Canta a noite toda perto de qualquer luz acesa.", pages: ["Greta já tentou expulsar os da Taverna dezenas de vezes. Eles sempre voltam.", "Alguns bêbados juram que o canto deles muda de tom conforme a noite avança.", "Possíveis drops (lore, não implementado): Perna Saltitante, Asa Fina, Antena Longa."], locked: false, unlockCondition: "Disponível desde o início", status: "estudado" },
  { id: "aranha-do-bosque-sussurrante", name: "Aranha do Bosque Sussurrante", type: "inseto", rarity: "incomum", suggestedLevel: 5, habitat: "Teias entre copas altas", regionId: "bosque-sussurrante", dangerLevel: "media", icon: "🕷️", description: "Tece teias entre árvores altas demais para qualquer humano alcançar.", pages: ["Raramente desce ao chão, exceto para caçar.", "Idris garante que uma teia dela já segurou o peso de um homem adulto.", "Possíveis drops (lore, não implementado): Teia Resistente, Perna Longa, Presa Fina."], locked: false, unlockCondition: "Disponível desde o início", status: "visto", connections: { npcKey: "viajante", npcNote: "Idris garante que uma teia dela já segurou o peso de um homem adulto." } },
  { id: "libelula-do-pantano", name: "Libélula do Pântano", type: "inseto", rarity: "incomum", suggestedLevel: 4, habitat: "Água parada e vegetação densa", regionId: "pantano-podre", dangerLevel: "baixa", icon: "🪰", description: "Voa em padrões que parecem, de longe, desenhados de propósito.", pages: ["Aparece só perto de água parada, nunca de água corrente.", "Yannick já passou uma tarde inteira tentando desenhar o padrão de voo dela. Desistiu.", "Possíveis drops (lore, não implementado): Asa Iridescente, Corpo Fino, Olho Composto."], locked: false, unlockCondition: "Disponível desde o início", status: "estudado" },
  { id: "escaravelho-das-minas", name: "Escaravelho das Minas", type: "inseto", rarity: "incomum", suggestedLevel: 6, habitat: "Túneis próprios dentro das minas", regionId: "minas-abandonadas", dangerLevel: "media", icon: "🪲", description: "Cava túneis próprios, ignorando completamente os já existentes.", pages: ["Mineiros o consideram sinal de boa sorte, apesar de nunca explicarem por quê.", "Alguns juram que ele consegue sentir veios de minério antes de qualquer humano.", "Possíveis drops (lore, não implementado): Casco Metálico, Mandíbula Forte, Antena Curta."], locked: false, unlockCondition: "Disponível desde o início", status: "visto", connections: { itemSlug: "luvas-forjadas-minas-abandonadas", npcKey: "ferreiro", npcNote: "Borin acha que o escaravelho sente veio de minério antes de qualquer mineiro." } },
  { id: "vespa-de-vidro-do-deserto", name: "Vespa de Vidro do Deserto", type: "inseto", rarity: "raro", suggestedLevel: 9, habitat: "Ninhos dentro da areia vitrificada", regionId: "deserto-de-vidro", dangerLevel: "alta", icon: "🐝", description: "As asas cortam como lâmina fina quando ela voa rápido demais.", pages: ["Constrói ninhos dentro da própria areia vitrificada, um mistério em si.", "Ninguém que já foi cortado por uma esqueceu a experiência.", "Possíveis drops (lore, não implementado): Asa Cortante, Ferrão de Vidro, Casco Translúcido."], locked: false, unlockCondition: "Disponível desde o início", status: "estudado" },
  { id: "centopeia-das-ruinas", name: "Centopeia das Ruínas", type: "inseto", rarity: "raro", suggestedLevel: 10, habitat: "Frestas estreitas entre pedras antigas", regionId: "ruinas-esquecidas", dangerLevel: "alta", icon: "🐛", description: "Vive nas frestas mais estreitas entre as pedras antigas.", pages: ["Cresce mais do que qualquer centopeia deveria, segundo os estudiosos.", "Alaric se recusa a guardar uma no Museu, viva ou morta.", "Possíveis drops (lore, não implementado): Casco Segmentado, Perna Fina, Presa Curva."], locked: false, unlockCondition: "Disponível desde o início", status: "visto" },
  { id: "mariposa-da-fortaleza", name: "Mariposa da Fortaleza", type: "inseto", rarity: "raro", suggestedLevel: 11, habitat: "Escuridão completa dos corredores internos", regionId: "fortaleza-sombria", dangerLevel: "media", icon: "🦋", description: "Só voa em completa escuridão, nunca perto de luz.", pages: ["Ninguém sabe do que ela se alimenta lá dentro.", "Guardas juram que o pó das asas dela apaga tochas.", "Possíveis drops (lore, não implementado): Pó de Asa, Antena Longa, Casco Escuro."], locked: false, unlockCondition: "Disponível desde o início", status: "estudado" },
  { id: "rainha-formiga-do-formigueiro-profundo", name: "Rainha-Formiga do Formigueiro Profundo", type: "inseto", rarity: "muito-raro", suggestedLevel: 16, habitat: "Centro de formigueiros antigos", regionId: "planicie-dourada", dangerLevel: "alta", icon: "🐜", description: "Nunca sai do centro do formigueiro, protegida por gerações de operárias.", pages: ["Alguns formigueiros da Planície Dourada existem há mais tempo que a própria Capital.", "Um estudioso passou anos tentando encontrar uma. Nunca encontrou.", "Possíveis drops (lore, não implementado): Casco Real, Mandíbula Imensa, Ferrão Grosso."], locked: true, unlockCondition: "Desconhecida", status: "bloqueado" },
  { id: "o-enxame-sem-fim", name: "O Enxame Sem Fim", type: "inseto", rarity: "lendaria", suggestedLevel: 19, habitat: "Clareira específica, uma vez por geração", regionId: "bosque-sussurrante", dangerLevel: "letal", icon: "🐝", description: "Aparece uma vez a cada geração, cobrindo uma clareira inteira.", pages: ["As últimas três aparições coincidem com mudanças grandes no Reino, segundo Alaric.", "Ninguém sabe se é um enxame só ou vários agindo juntos.", "Possíveis drops (lore, não implementado): Enxame Capturado, Asa Coletiva, Mel Escuro."], locked: true, unlockCondition: "Desconhecida", status: "bloqueado" },

  // ---- Mortos-vivos (12): 4 comum · 3 incomum · 2 raro · 2 muito-raro · 1 lendária ----
  { id: "esqueleto-de-sentinela", name: "Esqueleto de Sentinela", type: "morto-vivo", rarity: "comum", suggestedLevel: 3, habitat: "Postos de guarda abandonados", regionId: "ruinas-esquecidas", dangerLevel: "media", icon: "💀", description: "Continua de posto, mesmo sem ninguém mais pra vigiar.", pages: ["Ninguém sabe há quantas gerações ele está ali parado.", "Alaric já tentou catalogar a armadura dele. O esqueleto não deixou.", "Possíveis drops (lore, não implementado): Osso Quebrado, Fragmento de Armadura, Elmo Enferrujado."], locked: false, unlockCondition: "Disponível desde o início", status: "visto" },
  { id: "zumbi-de-vila-abandonada", name: "Zumbi de Vila Abandonada", type: "morto-vivo", rarity: "comum", suggestedLevel: 3, habitat: "Casas vazias e ruas desertas", regionId: "pantano-podre", dangerLevel: "media", icon: "🧟", description: "Repete os mesmos passos, todos os dias, como se ainda tivesse rotina.", pages: ["Alguns moradores juram reconhecer o rosto de gente que já morreu há anos.", "Ninguém tem coragem de perguntar de perto.", "Possíveis drops (lore, não implementado): Roupa Rasgada, Osso Solto, Sapato Velho."], locked: false, unlockCondition: "Disponível desde o início", status: "estudado" },
  { id: "mao-rastejante", name: "Mão Rastejante", type: "morto-vivo", rarity: "comum", suggestedLevel: 2, habitat: "Terrenos alagados e lamacentos", regionId: "pantano-podre", dangerLevel: "baixa", icon: "🖐️", description: "Se move sozinha, sem dono nem explicação.", pages: ["Encontrada, mais de uma vez, longe de qualquer corpo.", "Ninguém quis levar uma pra casa como troféu, apesar da oferta.", "Possíveis drops (lore, não implementado): Dedo Ósseo, Unha Quebrada, Pele Ressecada."], locked: false, unlockCondition: "Disponível desde o início", status: "visto" },
  { id: "mumia-menor-das-areias", name: "Múmia Menor das Areias", type: "morto-vivo", rarity: "comum", suggestedLevel: 4, habitat: "Sepulturas rasas sob a areia", regionId: "deserto-de-vidro", dangerLevel: "media", icon: "🧻", description: "Enterrada superficialmente, sempre volta à superfície.", pages: ["Ninguém sabe se ela sai sozinha ou se algo a desenterra.", "Os panos dela nunca se desfazem, não importa o tempo.", "Possíveis drops (lore, não implementado): Faixa Antiga, Amuleto Partido, Pó Fino."], locked: false, unlockCondition: "Disponível desde o início", status: "estudado" },
  { id: "cavaleiro-sem-cabeca-da-estrada-velha", name: "Cavaleiro Sem Cabeça da Estrada Velha", type: "morto-vivo", rarity: "incomum", suggestedLevel: 6, habitat: "Trecho fixo de estrada antiga", regionId: "colinas-aridas", dangerLevel: "alta", icon: "🗡️", description: "Percorre sempre o mesmo trecho de estrada, todas as noites.", pages: ["Ninguém sabe seu nome, mas todo mundo conhece a estrada que ele guarda.", "Guardas evitam essa estrada à noite, mesmo sendo o caminho mais curto.", "Possíveis drops (lore, não implementado): Elmo Vazio, Espada Cega, Armadura Fria."], locked: false, unlockCondition: "Disponível desde o início", status: "visto" },
  { id: "espectro-de-marinheiro", name: "Espectro de Marinheiro", type: "morto-vivo", rarity: "incomum", suggestedLevel: 7, habitat: "Perto de naufrágios na costa", regionId: "litoral-quebrado", dangerLevel: "media", icon: "👻", description: "Aparece só perto de naufrágios, nunca em água aberta.", pages: ["Alguns pescadores juram já ter conversado com um, brevemente.", "Ninguém que conversou concorda no que ele disse.", "Possíveis drops (lore, não implementado): Corda Molhada, Chapéu Encharcado, Moeda Antiga."], locked: false, unlockCondition: "Disponível desde o início", status: "estudado" },
  { id: "enforcado-da-forca-velha", name: "Enforcado da Forca Velha", type: "morto-vivo", rarity: "incomum", suggestedLevel: 6, habitat: "Estruturas de madeira abandonadas", regionId: "ruinas-esquecidas", dangerLevel: "alta", icon: "🪢", description: "Balança mesmo sem vento nenhum.", pages: ["Ninguém sabe o crime, nem se houve um de verdade.", "A corda nunca se rompe, não importa quanto tempo passe.", "Possíveis drops (lore, não implementado): Corda Velha, Roupa Rasgada, Anel Simples."], locked: false, unlockCondition: "Disponível desde o início", status: "visto" },
  { id: "guardiao-osseo-da-ultima-coroa", name: "Guardião Ósseo da Última Coroa", type: "morto-vivo", rarity: "raro", suggestedLevel: 10, habitat: "Corredores centrais das ruínas", regionId: "ruinas-esquecidas", dangerLevel: "alta", icon: "⚔️", description: "Protege um trecho específico das Ruínas, sem descanso.", pages: ["Dizem que já foi um soldado da guarda real, há muito tempo.", "Nenhum registro confirma seu nome, apesar de vários já terem tentado descobrir.", "Possíveis drops (lore, não implementado): Escudo Antigo, Elmo Real, Osso Reforçado."], locked: false, unlockCondition: "Disponível desde o início", status: "estudado", connections: { itemSlug: "elmo-guardiao-ruinas", npcKey: "curador", npcNote: "Alaric acredita que ele já foi um soldado da guarda real, há muito tempo." } },
  { id: "bruxa-cinza-da-fortaleza", name: "Bruxa Cinza da Fortaleza", type: "morto-vivo", rarity: "raro", suggestedLevel: 12, habitat: "Salões silenciosos da fortaleza", regionId: "fortaleza-sombria", dangerLevel: "letal", icon: "🧙‍♀️", description: "Só fala quando alguém realmente escuta.", pages: ["Ninguém sabe se ela já foi viva de verdade ou se sempre foi assim.", "Zoltar se recusa a falar sobre ela em detalhes.", "Possíveis drops (lore, não implementado): Manto Cinzento, Cajado Quebrado, Frasco Vazio."], locked: false, unlockCondition: "Disponível desde o início", status: "visto" },
  { id: "o-rei-sem-sepultura", name: "O Rei Sem Sepultura", type: "morto-vivo", rarity: "muito-raro", suggestedLevel: 16, habitat: "Corredores mais antigos da fortaleza", regionId: "fortaleza-sombria", dangerLevel: "letal", icon: "👑", description: "Anda pelos corredores mais antigos, sozinho, sem pressa.", pages: ["Nenhum historiador confirma qual rei foi, apesar das teorias.", "Alaric acredita que é o mesmo rei mencionado em relatos antigos, mas nunca provou.", "Possíveis drops (lore, não implementado): Coroa Partida, Manto Real, Cetro Quebrado."], locked: true, unlockCondition: "Desconhecida", status: "bloqueado" },
  { id: "a-viuva-da-ponte", name: "A Viúva da Ponte", type: "morto-vivo", rarity: "muito-raro", suggestedLevel: 17, habitat: "Ponte antiga sobre um rio seco", regionId: "colinas-aridas", dangerLevel: "alta", icon: "👻", description: "Espera, todas as noites, no mesmo ponto da ponte antiga.", pages: ["Ninguém sabe quem ela esperava, nem se um dia ele chegou.", "Alguns viajantes deixam flores na ponte, só por precaução.", "Possíveis drops (lore, não implementado): Véu Rasgado, Anel de Casamento, Flor Seca."], locked: true, unlockCondition: "Desconhecida", status: "bloqueado" },
  { id: "o-exercito-esquecido", name: "O Exército Esquecido", type: "morto-vivo", rarity: "lendaria", suggestedLevel: 22, habitat: "Pátio principal da fortaleza, só à noite", regionId: "fortaleza-sombria", dangerLevel: "letal", icon: "⚔️", description: "Aparece completo, em formação, e desaparece antes do amanhecer.", pages: ["Nenhum relato concorda em quantos soldados realmente são.", "Alaric dedicou um capítulo inteiro do Museu só a teorias sobre eles.", "Possíveis drops (lore, não implementado): Estandarte Rasgado, Armadura Completa, Espada de Comando."], locked: true, unlockCondition: "Desconhecida", status: "bloqueado" },

  // ---- Espíritos (12): 4 comum · 3 incomum · 2 raro · 2 muito-raro · 1 lendária ----
  { id: "sussurro-do-vento", name: "Sussurro do Vento", type: "espirito", rarity: "comum", suggestedLevel: 1, habitat: "Encostas abertas ao vento", regionId: "colinas-aridas", dangerLevel: "baixa", icon: "💨", description: "Só é notado quando o vento para de repente.", pages: ["Pastores dizem que é normal, e seguem trabalhando sem se abalar.", "Ninguém já viu, só ouviu.", "Possíveis drops (lore, não implementado): Eco Capturado, Pena Solta, Poeira Fina."], locked: false, unlockCondition: "Disponível desde o início", status: "visto" },
  { id: "luz-errante-do-pantano", name: "Luz Errante do Pântano", type: "espirito", rarity: "comum", suggestedLevel: 2, habitat: "Trilhas enlameadas ao anoitecer", regionId: "pantano-podre", dangerLevel: "baixa", icon: "🌫️", description: "Guia viajantes pro caminho errado, na maioria das vezes sem querer.", pages: ["Ninguém sabe se ela tem intenção ou só existe assim.", "Alguns juram que ela muda de cor dependendo de quem a segue.", "Possíveis drops (lore, não implementado): Fragmento de Luz, Névoa Capturada, Vidro Embaçado."], locked: false, unlockCondition: "Disponível desde o início", status: "estudado", connections: { npcKey: "taverneira", npcNote: "Greta diz que é essa luz que os viajantes juram ver no Pântano à noite.", rumor: "Um viajante jura ter visto luzes no Pântano Podre à noite." } },
  { id: "eco-da-capital-velha", name: "Eco da Capital Velha", type: "espirito", rarity: "comum", suggestedLevel: 2, habitat: "Becos vazios à noite", regionId: "porto-do-amanhecer", dangerLevel: "baixa", icon: "🔔", description: "Repete sons antigos em becos vazios, sem motivo aparente.", pages: ["Moradores mais velhos dizem que já era assim antes deles nascerem.", "O sino da torre, dizem, é onde ele mais aparece.", "Possíveis drops (lore, não implementado): Som Preso, Sino Rachado, Poeira Antiga."], locked: false, unlockCondition: "Disponível desde o início", status: "visto" },
  { id: "sombra-da-vela-apagada", name: "Sombra da Vela Apagada", type: "espirito", rarity: "comum", suggestedLevel: 3, habitat: "Cômodos fechados sem janelas", regionId: "porto-do-amanhecer", dangerLevel: "baixa", icon: "🕯️", description: "Aparece só quando uma vela apaga sozinha.", pages: ["Ninguém sabe se ela apaga a vela ou só aparece depois.", "Miriam mantém uma vela sempre acesa na Biblioteca, só por garantia.", "Possíveis drops (lore, não implementado): Cera Fria, Sombra Capturada, Pavio Queimado."], locked: false, unlockCondition: "Disponível desde o início", status: "estudado" },
  { id: "pranto-da-ponte-velha", name: "Pranto da Ponte Velha", type: "espirito", rarity: "incomum", suggestedLevel: 6, habitat: "Perto de água corrente, à noite", regionId: "colinas-aridas", dangerLevel: "media", icon: "😢", description: "Chora baixinho perto da água, sem nunca se mostrar.", pages: ["Ninguém sabe se é o mesmo espírito da Viúva da Ponte ou algo diferente.", "Alguns viajantes evitam a ponte à noite só por causa do choro.", "Possíveis drops (lore, não implementado): Lágrima Congelada, Véu Molhado, Eco de Choro."], locked: false, unlockCondition: "Disponível desde o início", status: "visto" },
  { id: "guardiao-silencioso-das-ruinas", name: "Guardião Silencioso das Ruínas", type: "espirito", rarity: "incomum", suggestedLevel: 7, habitat: "Câmaras centrais das ruínas", regionId: "ruinas-esquecidas", dangerLevel: "media", icon: "🌫️", description: "Observa exploradores sem nunca interferir.", pages: ["Alguns juram que ele afasta perigos maiores, sem ninguém perceber.", "Alaric acredita que ele protege as Ruínas há mais tempo que qualquer registro.", "Possíveis drops (lore, não implementado): Névoa Antiga, Pedra Fria, Eco de Passos."], locked: false, unlockCondition: "Disponível desde o início", status: "estudado", connections: { itemSlug: "amuleto-guardiao-ruinas", npcKey: "curador", npcNote: "Alaric acredita que ele protege as Ruínas há mais tempo que qualquer registro." } },
  { id: "espirito-da-fogueira-apagada", name: "Espírito da Fogueira Apagada", type: "espirito", rarity: "incomum", suggestedLevel: 6, habitat: "Acampamentos abandonados", regionId: "bosque-sussurrante", dangerLevel: "media", icon: "🔥", description: "Aparece só onde uma fogueira foi abandonada acesa.", pages: ["Alguns caçadores juram que ele reacende o fogo sozinho, à noite.", "Kade jura que uma vez ele reacendeu uma fogueira na Arena, sem explicação.", "Possíveis drops (lore, não implementado): Brasa Fria, Fumaça Presa, Cinza Quente."], locked: false, unlockCondition: "Disponível desde o início", status: "visto" },
  { id: "vulto-do-deserto-de-vidro", name: "Vulto do Deserto de Vidro", type: "espirito", rarity: "raro", suggestedLevel: 11, habitat: "Dunas durante tempestades de areia", regionId: "deserto-de-vidro", dangerLevel: "alta", icon: "👤", description: "Aparece só durante tempestades de areia, nunca antes ou depois.", pages: ["Alguns viajantes juram que ele os guiou pra fora da tempestade.", "Ninguém sabe se ele é benevolente ou só indiferente.", "Possíveis drops (lore, não implementado): Areia Vitrificada, Vulto Capturado, Vidro Quente."], locked: false, unlockCondition: "Disponível desde o início", status: "estudado" },
  { id: "voz-da-fortaleza-sombria", name: "Voz da Fortaleza Sombria", type: "espirito", rarity: "raro", suggestedLevel: 12, habitat: "Corredores profundos da fortaleza", regionId: "fortaleza-sombria", dangerLevel: "alta", icon: "🗣️", description: "Sussurra frases incompletas, nunca a mesma duas vezes.", pages: ["Ninguém que já ouviu concorda no que ela disse de verdade.", "Zoltar tentou registrar as frases. Desistiu depois da terceira tentativa.", "Possíveis drops (lore, não implementado): Sussurro Capturado, Eco Sombrio, Fragmento de Voz."], locked: false, unlockCondition: "Disponível desde o início", status: "visto", connections: { npcKey: "alquimista", npcNote: "Zoltar tentou registrar as frases dela. Desistiu depois da terceira tentativa.", rumor: "Ouviram cantoria vindo da Fortaleza Sombria. Ninguém foi conferir.", bookId: "misterios-da-fortaleza-sombria" } },
  { id: "o-guardiao-sem-rosto", name: "O Guardião Sem Rosto", type: "espirito", rarity: "muito-raro", suggestedLevel: 17, habitat: "Perto da estátua sem rosto da capital antiga", regionId: "ruinas-esquecidas", dangerLevel: "letal", icon: "🌫️", description: "Vigia a estátua sem rosto da Última Coroa, ou é ele mesmo a estátua.", pages: ["Ninguém sabe se é um espírito ou apenas uma lenda que ganhou vida própria.", "Alaric se recusa a comentar essa teoria específica.", "Possíveis drops (lore, não implementado): Máscara Vazia, Pedra Polida, Eco Antigo."], locked: true, unlockCondition: "Desconhecida", status: "bloqueado", connections: { npcKey: "curador", npcNote: "Alaric se recusa terminantemente a comentar essa teoria específica." } },
  { id: "a-dama-do-amanhecer", name: "A Dama do Amanhecer", type: "espirito", rarity: "muito-raro", suggestedLevel: 18, habitat: "Praia leste, no exato nascer do sol", regionId: "porto-do-amanhecer", dangerLevel: "media", icon: "🌅", description: "Aparece só no exato instante do nascer do sol, uma vez por estação.", pages: ["Alguns acreditam que ela é mais antiga que a própria Capital.", "O nome do Porto do Amanhecer vem, segundo alguns, dela mesma.", "Possíveis drops (lore, não implementado): Luz Capturada, Véu Dourado, Orvalho Eterno."], locked: true, unlockCondition: "Desconhecida", status: "bloqueado" },
  { id: "o-silencio-antes-da-tempestade", name: "O Silêncio Antes da Tempestade", type: "espirito", rarity: "lendaria", suggestedLevel: 21, habitat: "Picos mais altos, minutos antes de tempestades", regionId: "picos-congelados", dangerLevel: "letal", icon: "🌪️", description: "Aparece só nos minutos antes das piores tempestades dos Picos.", pages: ["Alguns exploradores usam a aparição dele como aviso pra recuar a tempo.", "Ninguém sabe se ele causa a tempestade ou só a antecipa.", "Possíveis drops (lore, não implementado): Silêncio Capturado, Gelo Eterno, Vento Preso."], locked: true, unlockCondition: "Desconhecida", status: "bloqueado" },

  // ---- Constructos (12): 4 comum · 3 incomum · 3 raro · 1 muito-raro · 1 lendária ----
  { id: "boneco-de-palha-animado", name: "Boneco de Palha Animado", type: "construto", rarity: "comum", suggestedLevel: 2, habitat: "Meio de plantações", regionId: "planicie-dourada", dangerLevel: "baixa", icon: "🎭", description: "Fica parado no meio da plantação até alguém chegar perto.", pages: ["Ninguém lembra quem o encantou pela primeira vez.", "Alguns fazendeiros trocam a roupa dele todo ano, por tradição.", "Possíveis drops (lore, não implementado): Palha Trançada, Botão Velho, Pano Remendado."], locked: false, unlockCondition: "Disponível desde o início", status: "visto" },
  { id: "golem-de-barro-pequeno", name: "Golem de Barro Pequeno", type: "construto", rarity: "comum", suggestedLevel: 3, habitat: "Poças de lama seca", regionId: "pantano-podre", dangerLevel: "media", icon: "🗿", description: "Se forma sozinho quando a lama seca de um jeito específico.", pages: ["Desmancha em poucos dias, e outro se forma em outro lugar.", "Ninguém nunca viu dois ao mesmo tempo.", "Possíveis drops (lore, não implementado): Barro Endurecido, Argila Rachada, Pedra Molhada."], locked: false, unlockCondition: "Disponível desde o início", status: "estudado" },
  { id: "espantalho-de-ferro", name: "Espantalho de Ferro", type: "construto", rarity: "comum", suggestedLevel: 3, habitat: "Bordas de plantações antigas", regionId: "colinas-aridas", dangerLevel: "media", icon: "🛡️", description: "Protege plantações que já nem existem mais.", pages: ["Alguns fazendeiros o mantêm por hábito, não por necessidade.", "Borin garante que já consertou um sem lembrar quem pediu.", "Possíveis drops (lore, não implementado): Placa de Ferro, Parafuso Solto, Pano Velho."], locked: false, unlockCondition: "Disponível desde o início", status: "visto" },
  { id: "marionete-sem-dono", name: "Marionete Sem Dono", type: "construto", rarity: "comum", suggestedLevel: 2, habitat: "Lojas fechadas e depósitos", regionId: "porto-do-amanhecer", dangerLevel: "baixa", icon: "🎎", description: "Se move sozinha quando ninguém está olhando direito.", pages: ["Encontrada numa loja fechada há anos, sem explicação de como chegou lá.", "Ninguém quis comprar, mesmo de graça.", "Possíveis drops (lore, não implementado): Fio Cortado, Madeira Entalhada, Roupa em Miniatura."], locked: false, unlockCondition: "Disponível desde o início", status: "estudado" },
  { id: "golem-de-pedra-antiga-menor", name: "Golem de Pedra Menor", type: "construto", rarity: "incomum", suggestedLevel: 6, habitat: "Galerias profundas e escuras", regionId: "minas-abandonadas", dangerLevel: "alta", icon: "⚙️", description: "Guarda galerias que ninguém mais consegue identificar o propósito.", pages: ["Move-se devagar, mas nunca para completamente.", "Mineiros aprenderam a simplesmente andar ao redor dele, sem provocar.", "Possíveis drops (lore, não implementado): Fragmento de Pedra, Núcleo Rachado, Placa Gravada."], locked: false, unlockCondition: "Disponível desde o início", status: "visto" },
  { id: "sentinela-de-bronze-enferrujado", name: "Sentinela de Bronze Enferrujado", type: "construto", rarity: "incomum", suggestedLevel: 7, habitat: "Postos avançados das ruínas", regionId: "ruinas-esquecidas", dangerLevel: "alta", icon: "🛡️", description: "Continua de posto, ferrugem e tudo, há gerações.", pages: ["Alaric acredita que ele já protegia algo importante, esquecido há muito tempo.", "Ninguém já conseguiu identificar o que ele está protegendo, exatamente.", "Possíveis drops (lore, não implementado): Placa de Bronze, Engrenagem Presa, Parafuso Antigo."], locked: false, unlockCondition: "Disponível desde o início", status: "estudado" },
  { id: "boneco-de-cera-da-feira", name: "Boneco de Cera da Feira", type: "construto", rarity: "incomum", suggestedLevel: 5, habitat: "Barracas de feira antigas", regionId: "porto-do-amanhecer", dangerLevel: "media", icon: "🕯️", description: "Derrete um pouco a cada verão, e volta a se formar no inverno.", pages: ["Ninguém lembra quem o esculpiu originalmente.", "Crianças da Capital juram que o rosto dele muda, ano após ano.", "Possíveis drops (lore, não implementado): Cera Derretida, Pavio Antigo, Molde Rachado."], locked: false, unlockCondition: "Disponível desde o início", status: "visto" },
  { id: "guardiao-de-ferro-da-ultima-coroa", name: "Guardião de Ferro da Última Coroa", type: "construto", rarity: "raro", suggestedLevel: 11, habitat: "Salões centrais das ruínas", regionId: "ruinas-esquecidas", dangerLevel: "alta", icon: "⚙️", description: "Protegia algo importante. Ninguém mais sabe o quê.", pages: ["Encontrado ainda de pé, décadas depois de tudo ao redor ter caído.", "Alaric tentou mover um pra exposição. Não conseguiu nem arranhar.", "Possíveis drops (lore, não implementado): Placa Reforçada, Núcleo de Ferro, Engrenagem Grande."], locked: false, unlockCondition: "Disponível desde o início", status: "estudado", connections: { itemSlug: "luvas-guardiao-ruinas", npcKey: "curador", npcNote: "Alaric tentou mover um pra exposição do Museu. Não conseguiu nem arranhar." } },
  { id: "automato-do-deserto-de-vidro", name: "Autômato do Deserto de Vidro", type: "construto", rarity: "raro", suggestedLevel: 12, habitat: "Linha reta pelo meio do deserto", regionId: "deserto-de-vidro", dangerLevel: "alta", icon: "🤖", description: "Anda em linha reta pelo deserto, sem nunca desviar.", pages: ["Ninguém sabe seu destino, nem se ele sabe.", "Zoltar tentou conversar com um. Não obteve resposta.", "Possíveis drops (lore, não implementado): Vidro Fundido, Engrenagem de Vidro, Núcleo Translúcido."], locked: false, unlockCondition: "Disponível desde o início", status: "visto" },
  { id: "sentinela-congelada-dos-picos", name: "Sentinela Congelada dos Picos", type: "construto", rarity: "raro", suggestedLevel: 13, habitat: "Trilhas altas cobertas de gelo", regionId: "picos-congelados", dangerLevel: "letal", icon: "❄️", description: "Fica imóvel por meses, até algo se aproximar demais.", pages: ["Alguns exploradores confundem com uma estátua, até ser tarde demais.", "Roth garante que um já ficou parado tempo suficiente pra virar ponto de referência num mapa.", "Possíveis drops (lore, não implementado): Gelo Compacto, Núcleo Congelado, Placa Gelada."], locked: false, unlockCondition: "Disponível desde o início", status: "estudado", connections: { itemSlug: "botas-picos-congelados", npcKey: "guarda", npcNote: "Roth garante que uma sentinela já ficou parada tempo suficiente pra virar ponto de referência num mapa." } },
  { id: "o-guardiao-sem-instrucoes", name: "O Guardião Sem Instruções", type: "construto", rarity: "muito-raro", suggestedLevel: 17, habitat: "Salão mais profundo da fortaleza", regionId: "fortaleza-sombria", dangerLevel: "alta", icon: "🗿", description: "Continua executando uma tarefa que ninguém mais lembra qual era.", pages: ["Alguns acreditam que ele protege algo que já nem existe mais.", "Alaric passou meses tentando decifrar as inscrições na base dele. Ainda tenta.", "Possíveis drops (lore, não implementado): Núcleo Antigo, Placa Inscrita, Engrenagem Complexa."], locked: true, unlockCondition: "Desconhecida", status: "bloqueado" },
  { id: "o-primeiro-automato", name: "O Primeiro Autômato", type: "construto", rarity: "lendaria", suggestedLevel: 24, habitat: "Câmara mais antiga das ruínas", regionId: "ruinas-esquecidas", dangerLevel: "alta", icon: "⚙️", description: "Dizem que foi o primeiro construto já feito no Reino.", pages: ["Nenhum ferreiro atual sabe reproduzir a técnica usada nele.", "Borin diz que estudaria a vida inteira só pra entender uma junta dele.", "Possíveis drops (lore, não implementado): Núcleo Primordial, Placa Original, Engrenagem Perfeita."], locked: true, unlockCondition: "Desconhecida", status: "bloqueado" },

  // ---- Elementais (12): 4 comum · 3 incomum · 2 raro · 2 muito-raro · 1 lendária ----
  { id: "faisca-errante", name: "Faísca Errante", type: "elemental", rarity: "comum", suggestedLevel: 2, habitat: "Perto de forjas acesas por tempo demais", regionId: "porto-do-amanhecer", dangerLevel: "baixa", icon: "✨", description: "Aparece perto de qualquer forja acesa por tempo demais.", pages: ["Borin diz que toda forja atrai uma, mais cedo ou mais tarde.", "Algumas somem sozinhas. Outras precisam ser 'convencidas'.", "Possíveis drops (lore, não implementado): Fagulha Presa, Cinza Quente, Carvão Aceso."], locked: false, unlockCondition: "Disponível desde o início", status: "visto" },
  { id: "poca-viva", name: "Poça Viva", type: "elemental", rarity: "comum", suggestedLevel: 2, habitat: "Áreas alagadas rasas", regionId: "pantano-podre", dangerLevel: "baixa", icon: "💧", description: "Se move devagar, sempre em direção à água mais próxima.", pages: ["Ninguém sabe se ela busca algo ou só segue um instinto simples.", "Crianças gostam de seguir uma até ela desaparecer numa poça maior.", "Possíveis drops (lore, não implementado): Água Densa, Lodo Vivo, Gota Espessa."], locked: false, unlockCondition: "Disponível desde o início", status: "estudado" },
  { id: "brisa-teimosa", name: "Brisa Teimosa", type: "elemental", rarity: "comum", suggestedLevel: 1, habitat: "Campos abertos e ventosos", regionId: "planicie-dourada", dangerLevel: "baixa", icon: "🍃", description: "Sopra sempre contra o vento principal, sem explicação.", pages: ["Fazendeiros usam a direção dela pra prever mudanças de tempo.", "Alguns dizem que ela nunca sopra igual duas vezes.", "Possíveis drops (lore, não implementado): Ar Comprimido, Pena Levitando, Poeira Suspensa."], locked: false, unlockCondition: "Disponível desde o início", status: "visto" },
  { id: "barro-fervente", name: "Barro Fervente", type: "elemental", rarity: "comum", suggestedLevel: 3, habitat: "Poças pequenas dentro das minas", regionId: "minas-abandonadas", dangerLevel: "media", icon: "🌋", description: "Borbulha sozinho em poças pequenas dentro das minas.", pages: ["Mineiros aprenderam a identificar o barulho antes de chegar perto.", "Já apagou mais de uma tocha esquecida no chão.", "Possíveis drops (lore, não implementado): Barro Quente, Pedra Amolecida, Vapor Denso."], locked: false, unlockCondition: "Disponível desde o início", status: "estudado" },
  { id: "chama-baixa-do-acampamento", name: "Chama Baixa do Acampamento", type: "elemental", rarity: "incomum", suggestedLevel: 5, habitat: "Fogueiras mal apagadas", regionId: "bosque-sussurrante", dangerLevel: "media", icon: "🔥", description: "Aparece em fogueiras mal apagadas, à noite.", pages: ["Viajantes aprenderam a apagar bem o fogo, só por precaução.", "Alguns juram que ela ajuda a manter o calor até de manhã.", "Possíveis drops (lore, não implementado): Brasa Viva, Fumaça Densa, Cinza Ardente."], locked: false, unlockCondition: "Disponível desde o início", status: "visto" },
  { id: "redemoinho-das-colinas", name: "Redemoinho das Colinas", type: "elemental", rarity: "incomum", suggestedLevel: 6, habitat: "Encostas secas sem vento aparente", regionId: "colinas-aridas", dangerLevel: "media", icon: "🌀", description: "Levanta poeira em espiral, sem vento nenhum ao redor.", pages: ["Pastores acreditam que segue certos animais por longas distâncias.", "Alguns dizem que ele carrega vozes distantes dentro da poeira.", "Possíveis drops (lore, não implementado): Poeira Girante, Ar Denso, Pedra Polida pelo Vento."], locked: false, unlockCondition: "Disponível desde o início", status: "estudado" },
  { id: "nevoa-gelada-dos-picos", name: "Névoa Gelada dos Picos", type: "elemental", rarity: "incomum", suggestedLevel: 7, habitat: "Trilhas altas sem aviso prévio", regionId: "picos-congelados", dangerLevel: "media", icon: "❄️", description: "Cobre trilhas inteiras em minutos, sem aviso.", pages: ["Guias experientes sabem esperar, nunca atravessar.", "Alguns exploradores relatam vozes dentro da névoa. Ninguém confirma.", "Possíveis drops (lore, não implementado): Gelo Fino, Névoa Presa, Cristal de Frost."], locked: false, unlockCondition: "Disponível desde o início", status: "visto" },
  { id: "coracao-de-vidro-do-deserto", name: "Coração de Vidro do Deserto", type: "elemental", rarity: "raro", suggestedLevel: 11, habitat: "Interior de dunas específicas", regionId: "deserto-de-vidro", dangerLevel: "alta", icon: "🔶", description: "Pulsa devagar dentro de dunas específicas, como um coração de verdade.", pages: ["Ninguém sabe se está vivo, ou se só imita algo vivo.", "Zoltar dedicou anos tentando entender o padrão do pulso.", "Possíveis drops (lore, não implementado): Vidro Pulsante, Núcleo Translúcido, Areia Quente."], locked: false, unlockCondition: "Disponível desde o início", status: "estudado" },
  { id: "chama-profunda-da-fortaleza", name: "Chama Profunda da Fortaleza", type: "elemental", rarity: "raro", suggestedLevel: 12, habitat: "Câmaras internas da fortaleza", regionId: "fortaleza-sombria", dangerLevel: "letal", icon: "🔥", description: "Arde sem consumir nada ao redor, há gerações.", pages: ["Alguns acreditam que ela guarda algo importante dentro do fogo.", "Ninguém já conseguiu apagá-la, apesar de várias tentativas registradas.", "Possíveis drops (lore, não implementado): Chama Eterna, Cinza Fria, Carvão Intacto."], locked: false, unlockCondition: "Disponível desde o início", status: "visto" },
  { id: "o-rio-que-sobe", name: "O Rio Que Sobe", type: "elemental", rarity: "muito-raro", suggestedLevel: 16, habitat: "Curso d'água próximo ao litoral", regionId: "litoral-quebrado", dangerLevel: "alta", icon: "🌊", description: "Corre morro acima, contra toda lógica, uma vez por estação.", pages: ["Pescadores organizam a rotina inteira em torno dessa uma vez.", "Ninguém sabe pra onde a água vai depois.", "Possíveis drops (lore, não implementado): Água Ascendente, Espuma Densa, Pedra Molhada Sempre."], locked: true, unlockCondition: "Desconhecida", status: "bloqueado" },
  { id: "o-vento-que-lembra", name: "O Vento Que Lembra", type: "elemental", rarity: "muito-raro", suggestedLevel: 17, habitat: "Encostas altas e isoladas", regionId: "colinas-aridas", dangerLevel: "media", icon: "🌬️", description: "Carrega sons de conversas antigas, às vezes reconhecíveis.", pages: ["Alguns moradores juram já ter ouvido a própria voz, mais jovem, no vento.", "Ninguém recomenda escutar por tempo demais.", "Possíveis drops (lore, não implementado): Eco Antigo, Ar Denso de Memória, Poeira de Tempo."], locked: true, unlockCondition: "Desconhecida", status: "bloqueado" },
  { id: "o-coracao-da-tempestade", name: "O Coração da Tempestade", type: "elemental", rarity: "lendaria", suggestedLevel: 23, habitat: "Centro das piores tempestades já registradas", regionId: "picos-congelados", dangerLevel: "letal", icon: "⛈️", description: "Aparece só no centro das piores tempestades já registradas.", pages: ["Cada geração tem no máximo um relato confirmado dele.", "Alguns acreditam que ele É a tempestade, não só parte dela.", "Possíveis drops (lore, não implementado): Núcleo da Tempestade, Raio Capturado, Gelo Eterno."], locked: true, unlockCondition: "Desconhecida", status: "bloqueado" },

  // ---- Dragões (12): 4 comum · 3 incomum · 2 raro · 2 muito-raro · 1 lendária ----
  { id: "lagarto-alado-da-planicie", name: "Lagarto-Alado da Planície", type: "dragao", rarity: "comum", suggestedLevel: 3, habitat: "Céu baixo sobre os trigais", regionId: "planicie-dourada", dangerLevel: "media", icon: "🦎", description: "Voa baixo, raramente mais alto que uma árvore.", pages: ["Considerado por muitos um dragão jovem demais pra ser perigoso.", "Fazendeiros os espantam com barulho, não com força.", "Possíveis drops (lore, não implementado): Escama Pequena, Asa Fina, Garra Curta."], locked: false, unlockCondition: "Disponível desde o início", status: "visto", connections: { npcKey: "mestreArena", npcNote: "Kade acha que é isso que a criança da Taverna viu — não uma nuvem grande.", rumor: "Uma criança jura ter visto um dragão. Era uma nuvem grande." } },
  { id: "filhote-de-dragao-das-colinas", name: "Filhote de Dragão das Colinas", type: "dragao", rarity: "comum", suggestedLevel: 4, habitat: "Fendas rochosas nas encostas", regionId: "colinas-aridas", dangerLevel: "media", icon: "🐉", description: "Ainda aprende a voar, caindo mais do que decolando.", pages: ["A mãe nunca é vista por perto, o que preocupa mais que tranquiliza.", "Kade jura que já viu um tropeçar nas próprias asas.", "Possíveis drops (lore, não implementado): Escama Macia, Garra Pequena, Dente de Leite."], locked: false, unlockCondition: "Disponível desde o início", status: "estudado" },
  { id: "dragao-lagarto-do-pantano", name: "Dragão-Lagarto do Pântano", type: "dragao", rarity: "comum", suggestedLevel: 4, habitat: "Águas rasas e lamacentas", regionId: "pantano-podre", dangerLevel: "media", icon: "🐊", description: "Nada mais do que voa, na maior parte do tempo.", pages: ["Parece mais réptil comum que dragão, até abrir as asas.", "Alguns pescadores nem percebem a diferença até ser tarde.", "Possíveis drops (lore, não implementado): Escama Encharcada, Cauda Grossa, Dente Afiado."], locked: false, unlockCondition: "Disponível desde o início", status: "visto" },
  { id: "draconido-das-rochas", name: "Dracônido das Rochas", type: "dragao", rarity: "comum", suggestedLevel: 3, habitat: "Fendas e afloramentos rochosos", regionId: "colinas-aridas", dangerLevel: "baixa", icon: "🦎", description: "Se camufla tão bem entre pedras que a maioria passa direto.", pages: ["Prefere fugir a lutar, na esmagadora maioria das vezes.", "Roth garante que um já ficou parado perto do Portão Norte por dias sem ser notado.", "Possíveis drops (lore, não implementado): Escama Cinzenta, Garra Curta, Cauda Pequena."], locked: false, unlockCondition: "Disponível desde o início", status: "estudado" },
  { id: "dragao-das-minas", name: "Dragão das Minas", type: "dragao", rarity: "incomum", suggestedLevel: 7, habitat: "Galerias mais profundas e desconhecidas", regionId: "minas-abandonadas", dangerLevel: "alta", icon: "🐲", description: "Vive nas galerias mais profundas, longe de qualquer entrada conhecida.", pages: ["Mineiros evitam certos túneis só por precaução, mesmo sem prova de que ele more ali.", "Ninguém sabe o tamanho real dele — só rastros.", "Possíveis drops (lore, não implementado): Escama Escura, Garra Robusta, Dente Quebrado."], locked: false, unlockCondition: "Disponível desde o início", status: "visto" },
  { id: "serpente-alada-do-litoral", name: "Serpente Alada do Litoral", type: "dragao", rarity: "incomum", suggestedLevel: 8, habitat: "Águas costeiras profundas", regionId: "litoral-quebrado", dangerLevel: "alta", icon: "🐍", description: "Caça peixes grandes, mergulhando de altura considerável.", pages: ["Pescadores aprenderam a reconhecer a sombra dela na água antes de qualquer outra coisa.", "Alguns acreditam que é parente distante das serpentes marinhas de histórias antigas.", "Possíveis drops (lore, não implementado): Escama Molhada, Asa Membranosa, Dente Curvo."], locked: false, unlockCondition: "Disponível desde o início", status: "estudado", connections: { itemSlug: "colar-conchas", npcKey: "viajante", npcNote: "Idris acredita que ela é parente distante das serpentes marinhas de histórias antigas." } },
  { id: "dragao-de-gelo-jovem", name: "Dragão de Gelo Jovem", type: "dragao", rarity: "incomum", suggestedLevel: 8, habitat: "Fendas nevadas nas montanhas", regionId: "picos-congelados", dangerLevel: "alta", icon: "🐉", description: "Ainda não sopra gelo de verdade, só névoa fria.", pages: ["Exploradores relatam encontros breves, sempre à distância.", "Yannick tem um desenho detalhado, feito de memória, depois de um encontro rápido.", "Possíveis drops (lore, não implementado): Escama Congelada, Garra Fria, Dente de Gelo."], locked: false, unlockCondition: "Disponível desde o início", status: "visto", connections: { itemSlug: "espada-curva-picos-congelados", npcKey: "erudito", npcNote: "Yannick tem um desenho detalhado dele, feito de memória, depois de um encontro rápido." } },
  { id: "dragao-das-ruinas-esquecidas", name: "Dragão das Ruínas Esquecidas", type: "dragao", rarity: "raro", suggestedLevel: 12, habitat: "Entre as pedras mais antigas das ruínas", regionId: "ruinas-esquecidas", dangerLevel: "alta", icon: "🐲", description: "Dorme na maior parte do tempo, entre as pedras mais antigas.", pages: ["Alguns exploradores juram já ter dormido a poucos metros dele, sem perceber.", "Alaric acredita que ele nasceu depois das Ruínas caírem, não antes.", "Possíveis drops (lore, não implementado): Escama Antiga, Garra Grande, Dente Amarelado."], locked: false, unlockCondition: "Disponível desde o início", status: "estudado" },
  { id: "serpente-dragao-do-deserto-de-vidro", name: "Serpente-Dragão do Deserto de Vidro", type: "dragao", rarity: "raro", suggestedLevel: 13, habitat: "Sob a areia vitrificada", regionId: "deserto-de-vidro", dangerLevel: "alta", icon: "🐍", description: "Nada pela areia como se fosse água.", pages: ["Ninguém sabe como ela respira lá dentro, mas respira.", "Zoltar acredita que ela é mais velha que o próprio deserto vitrificado.", "Possíveis drops (lore, não implementado): Escama Vítrea, Presa de Vidro, Cauda Reluzente."], locked: false, unlockCondition: "Disponível desde o início", status: "visto" },
  { id: "o-dragao-da-fortaleza-sombria", name: "O Dragão da Fortaleza Sombria", type: "dragao", rarity: "muito-raro", suggestedLevel: 18, habitat: "Salão principal da fortaleza", regionId: "fortaleza-sombria", dangerLevel: "letal", icon: "🐉", description: "Raramente sai do salão principal, protegendo algo que ninguém identificou.", pages: ["Alguns acreditam que ele guarda a Fortaleza há mais tempo que qualquer rei já registrado.", "Ninguém que o viu de perto concorda na cor exata das escamas.", "Possíveis drops (lore, não implementado): Escama Sombria, Garra Imensa, Dente Negro."], locked: true, unlockCondition: "Desconhecida", status: "bloqueado" },
  { id: "a-dragoa-dos-picos-eternos", name: "A Dragoa dos Picos Eternos", type: "dragao", rarity: "muito-raro", suggestedLevel: 19, habitat: "Ninho oculto no alto das montanhas", regionId: "picos-congelados", dangerLevel: "letal", icon: "🐉", description: "Protege um ninho que ninguém jamais encontrou.", pages: ["Exploradores que se aproximam demais relatam apenas o som de asas, nunca a visão completa.", "Roth acredita que ela é a mãe de todo dragão de gelo já avistado na região.", "Possíveis drops (lore, não implementado): Escama Glacial, Garra Afiada, Ovo Intacto."], locked: true, unlockCondition: "Desconhecida", status: "bloqueado" },
  { id: "o-velho-das-terras-altas", name: "O Velho das Terras Altas", type: "dragao", rarity: "lendaria", suggestedLevel: 27, habitat: "Picos mais remotos das colinas", regionId: "colinas-aridas", dangerLevel: "letal", icon: "🐲", description: "Ninguém sabe a idade real, só que é mais velho que qualquer relato escrito.", pages: ["Alguns acreditam que ele viu a fundação do Reino com os próprios olhos.", "Alaric guardaria um capítulo inteiro do Museu só pra ele, se algum dia tivesse a chance.", "Possíveis drops (lore, não implementado): Escama Ancestral, Garra Lendária, Dente do Tempo."], locked: true, unlockCondition: "Desconhecida", status: "bloqueado" },

  // ---- Bestas (12): 4 comum · 3 incomum · 3 raro · 1 muito-raro · 1 lendária ----
  { id: "cao-selvagem-da-estrada", name: "Cão Selvagem da Estrada", type: "besta", rarity: "comum", suggestedLevel: 2, habitat: "Estradas abertas entre regiões", regionId: "planicie-dourada", dangerLevel: "baixa", icon: "🐕‍🦺", description: "Segue viajantes por quilômetros, sem nunca se aproximar demais.", pages: ["Alguns acreditam que já foram cães domésticos, há gerações.", "Idris garante que um já o seguiu pelo Reino inteiro.", "Possíveis drops (lore, não implementado): Pelagem Suja, Presa Pequena, Coleira Velha."], locked: false, unlockCondition: "Disponível desde o início", status: "visto", connections: { npcKey: "viajante", npcNote: "Idris garante que um já o seguiu pelo Reino inteiro.", travellerStoryId: "cao-sem-dono-que-sempre-aparece" } },
  { id: "coelho-das-colinas", name: "Coelho das Colinas", type: "besta", rarity: "comum", suggestedLevel: 1, habitat: "Tocas rasas nas encostas", regionId: "colinas-aridas", dangerLevel: "baixa", icon: "🐇", description: "Multiplica-se rápido demais pra qualquer fazendeiro controlar.", pages: ["Alguns consideram praga. Outros, sorte.", "Talia vende pé-de-coelho na feira, sempre com a mesma história duvidosa de origem.", "Possíveis drops (lore, não implementado): Pelagem Macia, Pata Traseira, Orelha Comprida."], locked: false, unlockCondition: "Disponível desde o início", status: "estudado" },
  { id: "porco-espinho-do-bosque", name: "Porco-Espinho do Bosque", type: "besta", rarity: "comum", suggestedLevel: 1, habitat: "Sob folhas caídas na floresta", regionId: "bosque-sussurrante", dangerLevel: "baixa", icon: "🦔", description: "Se enrola ao menor sinal de perigo, e espera.", pages: ["Raramente ataca — a defesa dele já é suficiente.", "Crianças aprendem cedo a não cutucar um, geralmente da pior forma possível.", "Possíveis drops (lore, não implementado): Espinho Solto, Pelagem Curta, Casco Pequeno."], locked: false, unlockCondition: "Disponível desde o início", status: "visto" },
  { id: "gato-selvagem-da-vila", name: "Gato Selvagem da Vila", type: "besta", rarity: "comum", suggestedLevel: 2, habitat: "Telhados e becos da capital", regionId: "porto-do-amanhecer", dangerLevel: "baixa", icon: "🐈‍⬛", description: "Ignora praticamente todo mundo, com raras exceções.", pages: ["Alguns moradores juram que ele escolhe quem alimentar, não o contrário.", "Greta garante que ele prefere a Taverna a qualquer outro lugar da Capital.", "Possíveis drops (lore, não implementado): Pelagem Malhada, Garra Curta, Bigode Solto."], locked: false, unlockCondition: "Disponível desde o início", status: "estudado" },
  { id: "lince-das-colinas", name: "Lince das Colinas", type: "besta", rarity: "incomum", suggestedLevel: 5, habitat: "Encostas ao entardecer", regionId: "colinas-aridas", dangerLevel: "media", icon: "🐆", description: "Caça sozinho, ao entardecer, quase sem ser visto.", pages: ["Pastores reconhecem o rastro antes de reconhecer o animal.", "Kade jura que treinaria com um, se conseguisse chegar perto o suficiente.", "Possíveis drops (lore, não implementado): Pelagem Malhada, Garra Afiada, Presa Curva."], locked: false, unlockCondition: "Disponível desde o início", status: "visto" },
  { id: "javali-cinza-da-fronteira", name: "Javali Cinza da Fronteira", type: "besta", rarity: "incomum", suggestedLevel: 6, habitat: "Bordas entre regiões", regionId: "colinas-aridas", dangerLevel: "media", icon: "🐗", description: "Mais agressivo que o javali comum, e bem maior.", pages: ["Vive nas bordas entre regiões, nunca se estabelecendo de vez em nenhuma.", "Borin forjou uma lança especial só pra caçadores desse aqui.", "Possíveis drops (lore, não implementado): Presa Longa, Couro Duro, Casco Rachado."], locked: false, unlockCondition: "Disponível desde o início", status: "estudado" },
  { id: "corvo-de-ferro", name: "Corvo-de-Ferro", type: "besta", rarity: "incomum", suggestedLevel: 5, habitat: "Telhados e torres da capital", regionId: "porto-do-amanhecer", dangerLevel: "baixa", icon: "🐦‍⬛", description: "Rouba qualquer coisa que brilhe, sem exceção.", pages: ["Talia já perdeu moedas pra um mais de uma vez, e nunca recuperou.", "Alguns moradores deixam objetos brilhantes de propósito, só pra distraí-lo de outra coisa.", "Possíveis drops (lore, não implementado): Pena Escura, Bico Afiado, Garra Pequena."], locked: false, unlockCondition: "Disponível desde o início", status: "visto", connections: { itemSlug: "capacete-penas-corvo", npcKey: "mercador", npcNote: "Talia já perdeu moedas pra um corvo-de-ferro mais de uma vez, e nunca recuperou.", travellerStoryId: "corvo-que-conta-ate-tres" } },
  { id: "urso-pardo-da-fronteira-norte", name: "Urso-Pardo da Fronteira Norte", type: "besta", rarity: "raro", suggestedLevel: 9, habitat: "Território extenso e isolado", regionId: "colinas-aridas", dangerLevel: "alta", icon: "🐻", description: "Território enorme, quase nunca cruzado por humanos.", pages: ["Guardas do Portão Norte o consideram o verdadeiro dono daquela fronteira.", "Roth garante que já negociou passagem com um, à sua maneira.", "Possíveis drops (lore, não implementado): Pelagem Densa, Garra Grossa, Presa Longa."], locked: false, unlockCondition: "Disponível desde o início", status: "estudado", connections: { itemSlug: "luvas-cacador-feras", npcKey: "guarda", npcNote: "Roth garante que já negociou passagem com um, à sua maneira.", travellerStoryId: "urso-que-chora-a-noite" } },
  { id: "pantera-das-ruinas", name: "Pantera das Ruínas", type: "besta", rarity: "raro", suggestedLevel: 10, habitat: "Sombras entre as pedras antigas", regionId: "ruinas-esquecidas", dangerLevel: "alta", icon: "🐆", description: "Caça entre as pedras antigas, quase invisível à noite.", pages: ["Exploradores aprenderam a checar as sombras duas vezes, sempre.", "Alaric acredita que ela vive ali há gerações, adaptada ao ambiente.", "Possíveis drops (lore, não implementado): Pelagem Escura, Garra Silenciosa, Presa Fina."], locked: false, unlockCondition: "Disponível desde o início", status: "visto", connections: { itemSlug: "botas-cacador-feras", npcKey: "curador", npcNote: "Alaric acredita que ela vive ali há gerações, adaptada ao ambiente." } },
  { id: "lobo-solitario-da-fortaleza", name: "Lobo Solitário da Fortaleza", type: "besta", rarity: "raro", suggestedLevel: 11, habitat: "Arredores isolados da fortaleza", regionId: "fortaleza-sombria", dangerLevel: "alta", icon: "🐺", description: "Vive sozinho, longe de qualquer matilha conhecida.", pages: ["Ninguém sabe por que ele escolheu viver tão perto de um lugar como aquele.", "Alguns acreditam que ele protege algo, à sua própria maneira.", "Possíveis drops (lore, não implementado): Pelagem Grisalha, Presa Longa, Olho Atento."], locked: false, unlockCondition: "Disponível desde o início", status: "estudado" },
  { id: "o-urso-de-duas-cabecas", name: "O Urso de Duas Cabeças", type: "besta", rarity: "muito-raro", suggestedLevel: 16, habitat: "Áreas remotas das montanhas", regionId: "picos-congelados", dangerLevel: "letal", icon: "🐻", description: "Avistado poucas vezes, sempre à distância segura.", pages: ["Alguns acreditam ser dois ursos muito próximos. Outros, algo diferente.", "Yannick tem um relato detalhado, mas nunca confirmado por mais ninguém.", "Possíveis drops (lore, não implementado): Pelagem Dupla, Garra Imensa, Presa Rara."], locked: true, unlockCondition: "Desconhecida", status: "bloqueado" },
  { id: "o-lobo-que-nao-envelhece", name: "O Lobo Que Não Envelhece", type: "besta", rarity: "lendaria", suggestedLevel: 22, habitat: "Trechos profundos da floresta", regionId: "bosque-sussurrante", dangerLevel: "alta", icon: "🐺", description: "Visto em relatos que remontam a gerações passadas, sempre com a mesma descrição.", pages: ["Alguns acreditam que é sempre o mesmo lobo. Outros, uma linhagem inteira.", "Yannick dedicaria a vida inteira só pra confirmar qual das teorias é verdadeira.", "Possíveis drops (lore, não implementado): Pelagem Eterna, Presa Ancestral, Olho Dourado."], locked: true, unlockCondition: "Desconhecida", status: "bloqueado" },

  // ---- Humanoides (12): 4 comum · 3 incomum · 3 raro · 1 muito-raro · 1 lendária ----
  { id: "bandido-de-estrada", name: "Bandido de Estrada", type: "humanoide", rarity: "comum", suggestedLevel: 2, habitat: "Emboscadas em estradas abertas", regionId: "planicie-dourada", dangerLevel: "media", icon: "🗡️", description: "Assalta viajantes desprevenidos, quase sempre em grupo.", pages: ["Alguns já foram fazendeiros, antes de uma colheita ruim demais.", "Roth prende os mesmos rostos com frequência incomoda.", "Possíveis drops (lore, não implementado): Faca Enferrujada, Bolsa Vazia, Capuz Surrado."], locked: false, unlockCondition: "Disponível desde o início", status: "visto" },
  { id: "batedor-das-colinas", name: "Batedor das Colinas", type: "humanoide", rarity: "comum", suggestedLevel: 3, habitat: "Pontos altos com boa visão", regionId: "colinas-aridas", dangerLevel: "media", icon: "🏹", description: "Observa viajantes de longe antes de decidir se aproxima ou não.", pages: ["Vive isolado, evitando a Capital sempre que possível.", "Idris já trocou informações com um, em vez de lutar.", "Possíveis drops (lore, não implementado): Arco Simples, Flecha Gasta, Capa Surrada."], locked: false, unlockCondition: "Disponível desde o início", status: "estudado" },
  { id: "pescador-renegado", name: "Pescador Renegado", type: "humanoide", rarity: "comum", suggestedLevel: 2, habitat: "Trechos afastados da costa", regionId: "litoral-quebrado", dangerLevel: "baixa", icon: "🎣", description: "Rouba peixe de redes alheias, quando ninguém está olhando.", pages: ["Foi expulso da vila por um motivo que ninguém quer repetir.", "Alguns pescadores locais já deixam peixe de propósito, só pra ele ir embora.", "Possíveis drops (lore, não implementado): Rede Rasgada, Faca de Pesca, Chapéu Surrado."], locked: false, unlockCondition: "Disponível desde o início", status: "visto" },
  { id: "vagabundo-das-ruinas", name: "Vagabundo das Ruínas", type: "humanoide", rarity: "comum", suggestedLevel: 3, habitat: "Entre as pedras das ruínas", regionId: "ruinas-esquecidas", dangerLevel: "media", icon: "🥾", description: "Vive entre as pedras, evitando contato com qualquer grupo.", pages: ["Alguns acreditam que ele sabe mais sobre as Ruínas do que qualquer estudioso.", "Alaric já tentou conversar com um. A conversa não durou muito.", "Possíveis drops (lore, não implementado): Farrapo, Faca Cega, Saco Vazio."], locked: false, unlockCondition: "Disponível desde o início", status: "estudado" },
  { id: "mercenario-sem-bandeira", name: "Mercenário Sem Bandeira", type: "humanoide", rarity: "incomum", suggestedLevel: 6, habitat: "Onde houver pagamento", regionId: "colinas-aridas", dangerLevel: "alta", icon: "⚔️", description: "Luta por quem pagar mais, sem lealdade fixa a ninguém.", pages: ["Alguns já trabalharam pra mais de um Reino ao mesmo tempo, sem contar pra nenhum dos dois.", "Kade recusa duelo com eles, por princípio.", "Possíveis drops (lore, não implementado): Espada Gasta, Armadura Remendada, Bolsa de Moedas."], locked: false, unlockCondition: "Disponível desde o início", status: "visto", connections: { npcKey: "mestreArena", npcNote: "Kade recusa duelo com eles, por princípio." } },
  { id: "cacador-de-recompensas", name: "Caçador de Recompensas", type: "humanoide", rarity: "incomum", suggestedLevel: 7, habitat: "Rotas comerciais e cidades pequenas", regionId: "planicie-dourada", dangerLevel: "alta", icon: "🎯", description: "Persegue alvos por regiões inteiras, sem desistir fácil.", pages: ["Alguns confundem com Guarda, até perceberem que não seguem regra nenhuma.", "Roth já teve que negociar limites com mais de um.", "Possíveis drops (lore, não implementado): Corda Resistente, Marca de Procurado, Adaga Curva."], locked: false, unlockCondition: "Disponível desde o início", status: "estudado" },
  { id: "eremita-das-montanhas", name: "Eremita das Montanhas", type: "humanoide", rarity: "incomum", suggestedLevel: 6, habitat: "Cabanas isoladas nas alturas", regionId: "picos-congelados", dangerLevel: "media", icon: "🧙", description: "Vive sozinho, há tanto tempo que esqueceu como conversar direito.", pages: ["Alguns exploradores relatam conselhos estranhos, mas surpreendentemente úteis.", "Zoltar acredita que ele sabe mais de alquimia do que qualquer alquimista da Capital.", "Possíveis drops (lore, não implementado): Cajado Torto, Manto Puído, Frasco Vazio."], locked: false, unlockCondition: "Disponível desde o início", status: "visto" },
  { id: "guerreiro-esquecido-das-ruinas", name: "Guerreiro Esquecido das Ruínas", type: "humanoide", rarity: "raro", suggestedLevel: 11, habitat: "Postos avançados de um exército extinto", regionId: "ruinas-esquecidas", dangerLevel: "alta", icon: "⚔️", description: "Ainda usa uma armadura de um exército que não existe mais.", pages: ["Ninguém sabe se ele sabe que a guerra dele já acabou.", "Alaric já tentou explicar. Não teve certeza se foi entendido.", "Possíveis drops (lore, não implementado): Armadura Antiga, Espada Cega, Emblema Desconhecido."], locked: false, unlockCondition: "Disponível desde o início", status: "estudado" },
  { id: "xama-da-tribo-perdida", name: "Xamã da Tribo Perdida", type: "humanoide", rarity: "raro", suggestedLevel: 12, habitat: "Clareiras profundas da floresta", regionId: "bosque-sussurrante", dangerLevel: "alta", icon: "🪶", description: "Fala com animais que ninguém mais consegue se aproximar.", pages: ["Alguns acreditam que a tribo dele desapareceu há gerações, deixando só ele.", "Yannick tentaria estudá-lo a vida inteira, se ele permitisse.", "Possíveis drops (lore, não implementado): Colar de Ossos, Cajado Emplumado, Pele Pintada."], locked: false, unlockCondition: "Disponível desde o início", status: "visto", connections: { npcKey: "erudito", npcNote: "Yannick tentaria estudá-lo a vida inteira, se ele permitisse." } },
  { id: "cavaleiro-sem-reino", name: "Cavaleiro Sem Reino", type: "humanoide", rarity: "raro", suggestedLevel: 13, habitat: "Passagens esquecidas da fortaleza", regionId: "fortaleza-sombria", dangerLevel: "alta", icon: "🛡️", description: "Ainda usa um brasão que ninguém reconhece mais.", pages: ["Alguns acreditam que o Reino dele caiu há muito tempo, e ele nunca soube.", "Alaric adoraria identificar o brasão, sem sucesso até agora.", "Possíveis drops (lore, não implementado): Brasão Desconhecido, Espada Nobre, Elmo Riscado."], locked: false, unlockCondition: "Disponível desde o início", status: "estudado" },
  { id: "o-mensageiro-que-nunca-chega", name: "O Mensageiro Que Nunca Chega", type: "humanoide", rarity: "muito-raro", suggestedLevel: 17, habitat: "Estradas abertas, sempre em trânsito", regionId: "planicie-dourada", dangerLevel: "media", icon: "📜", description: "Sempre a caminho de algum lugar, nunca visto duas vezes no mesmo ponto.", pages: ["Alguns acreditam que ele carrega uma mensagem há décadas, sem nunca entregar.", "Ninguém sabe pra quem é a mensagem, nem o que ela diz.", "Possíveis drops (lore, não implementado): Selo Lacrado, Carta Não Entregue, Bota Gasta."], locked: true, unlockCondition: "Desconhecida", status: "bloqueado" },
  { id: "o-ultimo-soldado", name: "O Último Soldado", type: "humanoide", rarity: "lendaria", suggestedLevel: 24, habitat: "Posto avançado esquecido da fortaleza", regionId: "fortaleza-sombria", dangerLevel: "letal", icon: "⚔️", description: "Ainda defende um posto de uma guerra que terminou há gerações.", pages: ["Nenhum registro confirma de que lado ele lutava, originalmente.", "Alaric acredita que identificá-lo resolveria um mistério inteiro do Museu.", "Possíveis drops (lore, não implementado): Armadura de Comando, Espada Histórica, Estandarte Perdido."], locked: true, unlockCondition: "Desconhecida", status: "bloqueado" },

  // ---- Aberrações (12): 4 comum · 3 incomum · 2 raro · 2 muito-raro · 1 lendária ----
  { id: "rato-de-duas-caudas", name: "Rato de Duas Caudas", type: "aberracao", rarity: "comum", suggestedLevel: 2, habitat: "Túneis e galerias escuras", regionId: "minas-abandonadas", dangerLevel: "baixa", icon: "🐀", description: "Nasce assim, sem explicação conhecida.", pages: ["Alguns mineiros acreditam que dá sorte encontrar um. Outros, o oposto.", "Yannick já catalogou mais de uma dezena de casos parecidos.", "Possíveis drops (lore, não implementado): Cauda Extra, Pelagem Rala, Dente Torto."], locked: false, unlockCondition: "Disponível desde o início", status: "visto" },
  { id: "sapo-de-olhos-multiplos", name: "Sapo de Olhos Múltiplos", type: "aberracao", rarity: "comum", suggestedLevel: 3, habitat: "Água parada e lodosa", regionId: "pantano-podre", dangerLevel: "media", icon: "🐸", description: "Enxerga em praticamente todas as direções ao mesmo tempo.", pages: ["Alguns acreditam que é resultado de algo na água do pântano.", "Ninguém consegue se aproximar de surpresa.", "Possíveis drops (lore, não implementado): Olho Extra, Pele Viscosa, Língua Elástica."], locked: false, unlockCondition: "Disponível desde o início", status: "estudado" },
  { id: "verme-de-pedra", name: "Verme de Pedra", type: "aberracao", rarity: "comum", suggestedLevel: 3, habitat: "Dentro de rochas sólidas", regionId: "colinas-aridas", dangerLevel: "media", icon: "🪱", description: "Se move dentro de rochas sólidas, deixando túneis perfeitos.", pages: ["Ninguém entende como ele consegue perfurar pedra tão facilmente.", "Alguns pastores usam os túneis dele como atalho, quando dá certo.", "Possíveis drops (lore, não implementado): Segmento Pétreo, Pó de Pedra, Baba Mineral."], locked: false, unlockCondition: "Disponível desde o início", status: "visto" },
  { id: "planta-carnivora-ana", name: "Planta Carnívora Anã", type: "aberracao", rarity: "comum", suggestedLevel: 2, habitat: "Solo úmido sob a copa das árvores", regionId: "bosque-sussurrante", dangerLevel: "baixa", icon: "🌱", description: "Pequena demais pra ser perigosa, mas insiste em tentar.", pages: ["Alguns viajantes já perderam um dedo de luva pra uma, por descuido.", "Idris jura que uma tentou comer sua bota inteira.", "Possíveis drops (lore, não implementado): Pétala Afiada, Seiva Grudenta, Raiz Retorcida."], locked: false, unlockCondition: "Disponível desde o início", status: "estudado" },
  { id: "sombra-com-dentes", name: "Sombra com Dentes", type: "aberracao", rarity: "incomum", suggestedLevel: 7, habitat: "Corredores sem qualquer luz", regionId: "fortaleza-sombria", dangerLevel: "alta", icon: "👤", description: "Some completamente na escuridão, só os dentes ficam visíveis.", pages: ["Guardas evitam corredores sem luz por causa dela, especificamente.", "Ninguém sabe se ela realmente morde, ou só assusta.", "Possíveis drops (lore, não implementado): Dente Flutuante, Sombra Densa, Escuridão Presa."], locked: false, unlockCondition: "Disponível desde o início", status: "visto" },
  { id: "fungo-pensante", name: "Fungo Pensante", type: "aberracao", rarity: "incomum", suggestedLevel: 6, habitat: "Troncos podres no pântano", regionId: "pantano-podre", dangerLevel: "media", icon: "🍄", description: "Reage a quem se aproxima, de um jeito que parece decisão, não instinto.", pages: ["Yannick acredita que ele se comunica de alguma forma com outros fungos próximos.", "Alguns juram que ele muda de cor quando alguém mente perto dele.", "Possíveis drops (lore, não implementado): Esporo Denso, Cogumelo Pulsante, Raiz Fúngica."], locked: false, unlockCondition: "Disponível desde o início", status: "estudado" },
  { id: "criatura-de-areia-movedica", name: "Criatura de Areia Movediça", type: "aberracao", rarity: "incomum", suggestedLevel: 7, habitat: "Dunas instáveis", regionId: "deserto-de-vidro", dangerLevel: "alta", icon: "🏜️", description: "Se forma e desmancha na areia, sem forma fixa.", pages: ["Viajantes aprenderam a nunca confiar em dunas 'estranhamente perfeitas'.", "Zoltar acredita que ela é feita de vidro derretido misturado com areia comum.", "Possíveis drops (lore, não implementado): Areia Compacta, Núcleo Instável, Vidro Fundido."], locked: false, unlockCondition: "Disponível desde o início", status: "visto" },
  { id: "serpente-de-vidro-menor", name: "Serpente de Vidro Menor", type: "aberracao", rarity: "raro", suggestedLevel: 10, habitat: "Sob a areia vitrificada", regionId: "deserto-de-vidro", dangerLevel: "alta", icon: "🐍", description: "Move-se sem deixar rastro, cortando a areia como água.", pages: ["Ninguém sabe explicar como ela respira, ou se precisa.", "Zoltar tem uma teoria inteira, mas admite que é só teoria.", "Possíveis drops (lore, não implementado): Escama de Vidro, Presa Afiada, Veneno Cristalizado."], locked: false, unlockCondition: "Disponível desde o início", status: "estudado", connections: { itemSlug: "luvas-deserto-vidro", npcKey: "alquimista", npcNote: "Zoltar tem uma teoria inteira sobre como ela respira, mas admite que é só teoria." } },
  { id: "olho-flutuante-das-ruinas", name: "Olho Flutuante das Ruínas", type: "aberracao", rarity: "raro", suggestedLevel: 11, habitat: "Corredores altos das ruínas", regionId: "ruinas-esquecidas", dangerLevel: "alta", icon: "👁️", description: "Flutua sozinho, observando tudo, sem corpo visível.", pages: ["Alguns exploradores relatam ter sido observados por dias, sem entender por quê.", "Alaric se recusa a manter um catalogado por muito tempo perto de si.", "Possíveis drops (lore, não implementado): Íris Flutuante, Membrana Fina, Fluido Viscoso."], locked: false, unlockCondition: "Disponível desde o início", status: "visto" },
  { id: "a-voz-sem-rosto", name: "A Voz Sem Rosto", type: "aberracao", rarity: "muito-raro", suggestedLevel: 17, habitat: "Profundezas sem luz da fortaleza", regionId: "fortaleza-sombria", dangerLevel: "letal", icon: "🔮", description: "Ninguém sabe descrever exatamente o que é, só o que sente perto dele.", pages: ["Todo relato sobre ela é vago, como se a própria memória se recusasse a guardar detalhes.", "Zoltar se recusa terminantemente a falar sobre essa.", "Possíveis drops (lore, não implementado): Fragmento Inominável, Eco Distorcido, Sombra Densa."], locked: true, unlockCondition: "Desconhecida", status: "bloqueado" },
  { id: "a-coisa-entre-as-pedras", name: "A Coisa Entre as Pedras", type: "aberracao", rarity: "muito-raro", suggestedLevel: 18, habitat: "Dentro da rocha sólida", regionId: "colinas-aridas", dangerLevel: "letal", icon: "🪨", description: "Vive literalmente dentro da rocha sólida, aparecendo só por rachaduras.", pages: ["Alguns acreditam que ela esteve ali antes das próprias colinas se formarem.", "Yannick tem pesadelos recorrentes desde que estudou o caso de perto.", "Possíveis drops (lore, não implementado): Fragmento Vivo, Pedra Pulsante, Pó Estranho."], locked: true, unlockCondition: "Desconhecida", status: "bloqueado" },
  { id: "o-que-nao-deveria-existir", name: "O Que Não Deveria Existir", type: "aberracao", rarity: "lendaria", suggestedLevel: 26, habitat: "Profundezas do deserto vitrificado", regionId: "deserto-de-vidro", dangerLevel: "letal", icon: "👁️", description: "Nenhuma descrição confiável concorda em nada, exceto que ele existe.", pages: ["Cada estudioso que já se aproximou o suficiente descreve algo completamente diferente.", "Alaric se recusa terminantemente a abrir uma exposição sobre ele.", "Possíveis drops (lore, não implementado): Fragmento Impossível, Amostra Instável, Vestígio Inexplicável."], locked: true, unlockCondition: "Desconhecida", status: "bloqueado" },

  // ============================================================
  // Sprint Wolves Ecosystem (Phase I) — 8 variantes de lobos, aprofundando
  // o ecossistema já existente (Lobos Cinzentos, Lobo Solitário da
  // Fortaleza, O Lobo Que Não Envelhece). Cada uma conectada a um item,
  // NPC, rumor, história de viajante e/ou livro reais, criados nesta
  // mesma Sprint.
  // ============================================================
  { id: "lobo-alfa", name: "Lobo Alfa", type: "besta", rarity: "raro", suggestedLevel: 14, habitat: "Coração da matilha, no centro do bosque", regionId: "bosque-sussurrante", dangerLevel: "alta", icon: "🐺", description: "Lidera a matilha sem precisar provar isso duas vezes.", pages: ["Raramente entra em combate direto — a matilha inteira se move para protegê-lo primeiro.", "Borin jura que o couro de um Alfa é quase impossível de conseguir sem rasgos.", "Possíveis drops (lore, não implementado): Presa do Alfa, Pelagem de Líder, Garra Dominante."], locked: false, unlockCondition: "Disponível desde o início", status: "estudado", connections: { itemSlug: "presa-do-alfa", npcKey: "ferreiro", npcNote: "Borin jura que o couro de um Alfa é quase impossível de conseguir sem rasgos.", rumor: "Contam que o Lobo Alfa só aparece pra quem já enfrentou a matilha inteira e sobreviveu.", travellerStoryId: "uivo-que-lidera", bookId: "tratado-da-matilha" } },
  { id: "loba-prateada", name: "Loba Prateada", type: "besta", rarity: "raro", suggestedLevel: 13, habitat: "Trilhas afastadas da matilha principal", regionId: "bosque-sussurrante", dangerLevel: "alta", icon: "🐺", description: "Caça sozinha, longe da matilha, sempre retornando antes do amanhecer.", pages: ["Não é subordinada ao Alfa — opera por conta própria, por escolha.", "Yannick descreve a pelagem dela como quase brilhante sob luar, mesmo depois de curtida.", "Possíveis drops (lore, não implementado): Pelagem Prateada, Presa Curva, Olho Claro."], locked: false, unlockCondition: "Disponível desde o início", status: "estudado", connections: { itemSlug: "manto-da-loba-prateada", npcKey: "erudito", npcNote: "Yannick descreve a pelagem dela como quase brilhante sob luar, mesmo depois de curtida.", travellerStoryId: "loba-que-anda-sozinha", bookId: "tratado-da-matilha" } },
  { id: "filhote-de-lobo-perdido", name: "Filhote de Lobo Perdido", type: "besta", rarity: "comum", suggestedLevel: 2, habitat: "Bordas do bosque, longe da matilha", regionId: "bosque-sussurrante", dangerLevel: "baixa", icon: "🐺", description: "Separado da matilha, ainda aprendendo a sobreviver sozinho.", pages: ["Um dos poucos lobos que se aproxima de humanos sem hostilidade.", "Greta jura guardar uma presa de lobo há anos — talvez a dele mesmo.", "Possíveis drops (lore, não implementado): Presa de Leite, Pelagem Macia, Coleira Improvisada."], locked: false, unlockCondition: "Disponível desde o início", status: "visto", connections: { itemSlug: "coleira-do-filhote-perdido", npcKey: "taverneira", npcNote: "Greta jura guardar uma presa de lobo há anos — talvez a dele mesmo.", rumor: "Dizem que um filhote de lobo foi visto sozinho perto da Capital. Ninguém teve coragem de se aproximar.", travellerStoryId: "filhote-que-seguiu-um-viajante" } },
  { id: "lobo-das-colinas-aridas", name: "Lobo das Colinas Áridas", type: "besta", rarity: "comum", suggestedLevel: 4, habitat: "Encostas secas, longe de qualquer matilha grande", regionId: "colinas-aridas", dangerLevel: "media", icon: "🐺", description: "Caça sozinho — a terra ali não sustenta uma matilha inteira.", pages: ["Mais magro que o lobo do Bosque, adaptado à escassez de presas.", "Idris já cruzou com um duas vezes na mesma travessia.", "Possíveis drops (lore, não implementado): Pelagem Seca, Garra Fina, Presa Curta."], locked: false, unlockCondition: "Disponível desde o início", status: "visto", connections: { itemSlug: "botas-de-pelagem-seca", npcKey: "viajante", npcNote: "Idris já cruzou com um lobo das Colinas Áridas duas vezes na mesma travessia.", travellerStoryId: "lobos-que-nao-cacam-em-bando" } },
  { id: "lobo-do-pantano", name: "Lobo do Pântano", type: "besta", rarity: "incomum", suggestedLevel: 7, habitat: "Trilhas alagadas do pântano", regionId: "pantano-podre", dangerLevel: "media", icon: "🐺", description: "Atravessa água parada como se fosse chão firme.", pages: ["Adaptou-se à água melhor que qualquer outro lobo do Reino.", "Idris afirma que os lobos daqui nadam melhor do que caçam.", "Possíveis drops (lore, não implementado): Pelagem Encharcada, Garra Molhada, Presa Escorregadia."], locked: false, unlockCondition: "Disponível desde o início", status: "visto", connections: { itemSlug: "manto-de-pelagem-encharcada", npcKey: "viajante", npcNote: "Idris afirma que os lobos do Pântano Podre nadam melhor do que caçam.", rumor: "Um viajante afirma que os lobos do Pântano Podre nadam melhor do que caçam.", travellerStoryId: "lobo-que-nada-no-pantano" } },
  { id: "lobo-de-presas-de-gelo", name: "Lobo de Presas de Gelo", type: "besta", rarity: "raro", suggestedLevel: 12, habitat: "Fendas nevadas nos picos", regionId: "picos-congelados", dangerLevel: "alta", icon: "🐺", description: "Suas presas parecem refletir a luz da lua, como gelo puro.", pages: ["Exploradores relatam avistamentos breves, sempre à distância segura.", "Yannick nunca conseguiu confirmar se as presas realmente brilham, ou se é só a neve.", "Possíveis drops (lore, não implementado): Presa Gelada, Pelagem Congelada, Garra Cristalina."], locked: false, unlockCondition: "Disponível desde o início", status: "visto", connections: { itemSlug: "elmo-de-presas-de-gelo", npcKey: "erudito", npcNote: "Yannick nunca conseguiu confirmar se as presas realmente brilham, ou se é só a neve.", rumor: "Contam que existe um lobo nos Picos Congelados com presas que brilham como gelo puro.", travellerStoryId: "presas-que-brilham-na-neve" } },
  { id: "matilha-faminta", name: "Matilha Faminta", type: "besta", rarity: "incomum", suggestedLevel: 9, habitat: "Trechos densos do bosque, longe de presa fácil", regionId: "bosque-sussurrante", dangerLevel: "alta", icon: "🐺", description: "Cerca em silêncio absoluto, sem o uivo de aviso de costume.", pages: ["O encontro mais perigoso de todos, precisamente porque não avisa.", "Borin recusa forjar armadilhas pra lobo. Diz que não é esse tipo de ferreiro.", "Possíveis drops (lore, não implementado): Garras de Matilha, Pelagem Áspera, Presa Rachada."], locked: false, unlockCondition: "Disponível desde o início", status: "visto", connections: { itemSlug: "garras-de-matilha", npcKey: "ferreiro", npcNote: "Borin recusa forjar armadilhas pra lobo. Diz que não é esse tipo de ferreiro.", travellerStoryId: "matilha-que-cerca-em-silencio" } },
  { id: "o-lobo-marcado", name: "O Lobo Marcado", type: "besta", rarity: "muito-raro", suggestedLevel: 19, habitat: "Trechos mais profundos do bosque", regionId: "bosque-sussurrante", dangerLevel: "alta", icon: "🐺", description: "Magro, cicatrizado, impossível de encurralar.", pages: ["Alguns caçadores juram reconhecer sempre o mesmo lobo, marcado no focinho.", "Idris jura ter visto o mesmo lobo marcado em duas regiões diferentes, no mesmo dia.", "Possíveis drops (lore, não implementado): Pelagem Marcada, Presa Rachada, Garra Antiga."], locked: true, unlockCondition: "Desconhecida", status: "bloqueado", connections: { npcKey: "viajante", npcNote: "Idris jura ter visto o mesmo lobo marcado em duas regiões diferentes, no mesmo dia.", rumor: "Dizem que existe um lobo tão velho que já foi visto pela avó de quem conta a história agora.", travellerStoryId: "lobo-com-cicatriz-no-focinho" } },
];
