import type { ExpeditionStatus } from "@streamrpg/shared";

// Sprint Living Expeditions (MVP) — narrativa curta por estado da
// expedição, além do Encounter (Sprint Encounter System) já existente.
// O Encounter já dá UM evento estável por visita a um estado; esta
// camada é um "flicker" ambiente que troca a cada nova leitura (poll),
// mesmo sem o estado mudar — reforça a sensação de que a aventura
// continua acontecendo enquanto a aba fica parada. Nunca menciona
// recompensa, XP, número ou dano — só narrativa.
const PREPARING_NARRATIVES: string[] = [
  "O grupo revisa o equipamento.",
  "Alguém esqueceu água.",
  "O mapa parece incompleto.",
  "O cavalo se recusou a sair.",
  "Alguém amarra a bota pela terceira vez.",
  "A corda parece curta demais.",
  "Um dos sacos está pesado demais.",
  "Alguém verifica a bússola duas vezes.",
  "A comida foi dividida entre as mochilas.",
  "Um par de botas foi trocado de última hora.",
  "Alguém insiste em levar mais uma tocha.",
  "O grupo discute qual caminho seguir primeiro.",
  "Uma faca precisou ser afiada às pressas.",
  "Alguém verifica se trancou a porta de casa.",
  "O clima parece incerto pela manhã.",
  "Uma última checagem na armadura.",
  "Alguém amarra o cabelo antes de partir.",
  "O grupo se despede de quem fica.",
  "Falta pouco, mas ninguém quer ser o primeiro a sair.",
  "Um saco de provisões quase foi esquecido.",
  "Alguém reclama do peso da bagagem.",
  "O sol ainda não apareceu por completo.",
  "Um cinto foi ajustado mais uma vez.",
  "Alguém conta as flechas do carcaz.",
  "O grupo repassa o plano em voz baixa.",
  "Uma bota está apertada e ninguém percebeu antes.",
  "Alguém amarra o escudo nas costas.",
  "O cheiro de pão fresco ainda paira no ar.",
  "Falta decidir quem carrega a corda.",
  "Um cantil é enchido até a borda.",
  "Alguém verifica se a espada está na bainha certa.",
  "O grupo espera um sinal para partir.",
  "Uma última olhada para a Capital ao longe.",
  "Alguém amarra os cadarços com cuidado extra hoje.",
  "O ar da manhã ainda está frio.",
  "Um mapa é dobrado e guardado no bolso errado.",
  "Alguém verifica se trouxe fósforos.",
  "O grupo se organiza em fila, sem muita ordem.",
  "Uma última instrução é repetida em voz alta.",
  "Alguém aperta as correias da mochila.",
  "O silêncio antes da partida incomoda um pouco.",
  "Um par de luvas é vestido, meio surrado.",
  "Alguém pergunta se realmente precisam ir hoje.",
  "O grupo concorda, sem muita convicção.",
  "Uma corda extra é enrolada no ombro.",
  "Alguém verifica o horizonte, só para ter certeza.",
  "O barulho da cidade ainda ecoa atrás deles.",
  "Um último gole de água antes de partir.",
  "Alguém ajeita o capuz contra o vento.",
  "O grupo troca olhares, sem dizer nada.",
  "Uma bolsa de moedas é contada duas vezes.",
  "Alguém amarra um lenço no pescoço.",
  "O caminho à frente ainda parece distante.",
  "Um dos cavalos relincha, impaciente.",
  "Alguém verifica se a tenda foi bem dobrada.",
  "O grupo faz um último inventário, por precaução.",
  "Uma faca extra é guardada na bota.",
  "Alguém aperta o passo, ansioso para começar.",
  "O céu está claro, pelo menos por enquanto.",
  "Um dos viajantes reza baixinho antes de partir.",
  "Alguém verifica se o grupo está completo.",
  "O portão da Capital range ao ser aberto.",
  "Um último aceno para quem ficou para trás.",
  "Alguém amarra as botas com um nó duplo, hoje.",
  "O grupo respira fundo antes do primeiro passo.",
  "Uma provisão extra é enfiada no bolso, escondida.",
  "Alguém pergunta se alguém trouxe um mapa reserva.",
  "O vento começa a soprar, como se desse o sinal.",
  "Um dos viajantes olha para trás uma última vez.",
  "O grupo finalmente começa a caminhar.",
];

const EXPLORING_NARRATIVES: string[] = [
  "A trilha desapareceu.",
  "Pegadas recentes foram encontradas.",
  "O vento mudou.",
  "Um corvo acompanha o grupo.",
  "O caminho se estreita entre as árvores.",
  "Alguém escorrega numa pedra solta.",
  "O som de água corrente aparece ao longe.",
  "Uma trilha alternativa é notada, mas ignorada.",
  "O grupo faz uma pausa rápida para respirar.",
  "Nuvens começam a se formar no horizonte.",
  "Um cheiro estranho é notado no ar.",
  "Alguém aponta para algo ao longe, sem certeza do que é.",
  "O terreno fica mais irregular.",
  "Um galho quebra sozinho, sem vento nenhum.",
  "O grupo segue em silêncio por um trecho.",
  "Marcas estranhas são vistas numa árvore.",
  "Alguém tropeça numa raiz escondida.",
  "O caminho sobe de forma mais íngreme.",
  "Um som distante faz todos pararem por um instante.",
  "A vegetação muda repentinamente.",
  "Alguém consulta o mapa, sem muita certeza.",
  "O grupo atravessa um riacho raso.",
  "Uma sombra passa rápido demais para ser identificada.",
  "O silêncio da região incomoda um pouco.",
  "Alguém encontra uma pena grande no chão.",
  "O caminho se divide em dois, sem placa nenhuma.",
  "Um som de passos ecoa atrás do grupo.",
  "Alguém acha uma pedra com um formato estranho.",
  "O grupo decide seguir pela trilha mais longa.",
  "Uma névoa fina cobre parte do caminho.",
  "Alguém percebe que está sendo observado.",
  "O terreno começa a descer suavemente.",
  "Um cheiro de fumaça é notado, distante.",
  "O grupo evita uma poça de água escura.",
  "Alguém encontra restos de um acampamento antigo.",
  "O céu começa a escurecer mais cedo que o esperado.",
  "Um barulho de asas assusta o grupo por um instante.",
  "A trilha volta a aparecer, mais estreita.",
  "Alguém acha marcas de garras numa árvore.",
  "O grupo atravessa um campo aberto, exposto.",
  "Um eco estranho responde a um grito de teste.",
  "Alguém encontra uma flor que não reconhece.",
  "O caminho passa perto de um penhasco.",
  "Um silêncio súbito toma conta da região.",
  "Alguém sente que já passou por ali antes.",
  "O grupo segue as pegadas encontradas mais cedo.",
  "Uma trilha de formigas atravessa o caminho.",
  "O vento traz um cheiro de chuva.",
  "Alguém acha uma corda velha amarrada numa árvore.",
  "O grupo faz uma pausa à sombra de uma pedra grande.",
  "Um pássaro grande sobrevoa em círculos.",
  "Alguém percebe uma trilha recém-aberta na vegetação.",
  "O caminho atravessa uma área queimada, antiga.",
  "Um som de água corrente fica mais alto.",
  "Alguém acha uma bota velha, abandonada há tempo.",
  "O grupo segue por uma trilha mais alta, com melhor visão.",
  "Uma névoa espessa reduz a visibilidade por um momento.",
  "Alguém acha uma pegada maior do que o esperado.",
  "O terreno vira pedra sólida por um trecho.",
  "Um grito distante ecoa, e ninguém comenta.",
  "O grupo atravessa uma ponte de madeira instável.",
  "Alguém percebe marcas de fogo numa árvore caída.",
  "O caminho se torna quase invisível entre as pedras.",
  "Um cheiro forte de terra molhada surge de repente.",
  "Alguém encontra uma pequena caverna, ignorada por ora.",
  "O grupo segue em fila única por um trecho estreito.",
  "Um som de asas bate perto, sem que nada seja visto.",
  "Alguém acha restos de uma fogueira ainda morna.",
  "O caminho começa a descer em direção a um vale.",
  "O destino já pode ser avistado ao longe.",
];

const COMBATING_NARRATIVES: string[] = [
  "Ninguém imaginava que seriam tantos.",
  "As armas finalmente deixaram o silêncio.",
  "O primeiro golpe veio mais cedo que o esperado.",
  "O arqueiro perdeu a flecha... e a coragem.",
  "Um grito corta o ar antes de qualquer outra coisa.",
  "Alguém grita uma ordem que ninguém segue direito.",
  "O chão treme sob os primeiros passos apressados.",
  "Uma sombra se move rápido demais para ser vista com clareza.",
  "O grupo se posiciona em círculo, por instinto.",
  "Alguém escorrega no meio da confusão.",
  "Um escudo é erguido bem a tempo.",
  "O barulho de metal contra metal ecoa longe.",
  "Alguém grita para recuar, mas ninguém recua.",
  "O primeiro a atacar também é o primeiro a hesitar.",
  "Uma poeira densa se levanta do chão.",
  "Alguém percebe tarde demais que estava cercado.",
  "O grupo se aproxima, ombro a ombro.",
  "Um golpe erra por pouco.",
  "Alguém prende a respiração antes do confronto direto.",
  "O som de passos apressados vem de todas as direções.",
  "Uma arma cai no chão, e ninguém para para pegá-la.",
  "O grupo mantém a formação, por enquanto.",
  "Alguém grita o nome de outro companheiro, alto.",
  "O primeiro sangue ainda não foi derramado, mas está perto.",
  "Um golpe certeiro corta o silêncio.",
  "Alguém tropeça, mas se levanta rápido.",
  "O grupo avança devagar, testando o terreno.",
  "Um grito de dor é abafado pelo caos.",
  "Alguém segura a respiração antes do próximo movimento.",
  "O confronto parece durar mais do que realmente dura.",
  "Uma arma se choca contra uma superfície dura.",
  "Alguém percebe uma abertura e aproveita.",
  "O grupo se reorganiza no meio do combate.",
  "Um golpe é desviado por pouco.",
  "Alguém grita para que todos se cubram.",
  "O barulho da luta atrai mais atenção do que deveria.",
  "Uma respiração ofegante se destaca em meio ao caos.",
  "Alguém segura firme, mesmo com as mãos tremendo.",
  "O grupo avança em conjunto, sem hesitar dessa vez.",
  "Um golpe forte derruba algo, ou alguém.",
  "Alguém grita que está tudo sob controle. Não está.",
  "O confronto muda de direção repentinamente.",
  "Uma arma quebra no meio do combate.",
  "Alguém percebe que está lutando ao lado de um estranho, não de um amigo.",
  "O grupo resiste, mesmo cansado.",
  "Um golpe certeiro decide o rumo do confronto.",
  "Alguém grita de alívio, cedo demais.",
  "O silêncio depois de um golpe forte assusta mais que o próprio golpe.",
  "Uma última investida parece decidir tudo.",
  "Alguém cai, mas se levanta antes que alguém note.",
  "O grupo finalmente ganha vantagem no confronto.",
  "Um grito de vitória sai antes da hora certa.",
  "Alguém baixa a guarda cedo demais.",
  "O combate se arrasta por mais um instante tenso.",
  "Uma arma é reerguida com mãos trêmulas.",
  "Alguém percebe que o inimigo também está cansado.",
  "O grupo aperta o cerco, sentindo a vantagem.",
  "Um último golpe encerra o confronto.",
  "Alguém respira fundo, aliviado, mas sem baixar a guarda.",
  "O silêncio depois da luta parece esquisito.",
  "Alguém conta os companheiros, só para ter certeza.",
  "O grupo verifica os ferimentos uns dos outros.",
  "Uma arma é guardada com as mãos ainda tremendo.",
  "Alguém ri, nervoso, sem motivo aparente.",
  "O grupo se reorganiza, ainda tenso.",
  "Um dos companheiros ainda respira pesado.",
  "Alguém pergunta se está mesmo acabado.",
  "O grupo confirma, aos poucos, que sim.",
  "Uma poeira ainda paira no ar do confronto.",
  "O grupo respira, finalmente, com calma.",
];

const RESTING_NARRATIVES: string[] = [
  "A fogueira finalmente foi acesa.",
  "Alguém contou uma história exagerada.",
  "O silêncio parecia confortável.",
  "Um pão foi dividido entre todos.",
  "Alguém tira as botas, aliviado.",
  "O calor da fogueira espanta o frio da noite.",
  "Uma piada ruim arranca risadas mesmo assim.",
  "Alguém verifica os ferimentos com mais calma agora.",
  "O grupo se acomoda em volta do fogo.",
  "Uma canção baixa é cantarolada por alguém.",
  "Alguém estica as pernas, cansado da caminhada.",
  "O céu estrelado é notado pela primeira vez no dia.",
  "Uma discussão boba surge sobre quem cozinha melhor.",
  "Alguém cochila antes mesmo de terminar a refeição.",
  "O grupo divide o que sobrou das provisões.",
  "Uma risada alta quebra o silêncio da noite.",
  "Alguém remenda uma roupa rasgada à luz do fogo.",
  "O cheiro de comida quente anima todo mundo.",
  "Alguém convenceu o grupo a contar cada um uma história.",
  "O fogo estala baixinho, quase hipnotizante.",
  "Alguém aponta uma estrela e inventa um nome pra ela.",
  "O grupo ri de algo que aconteceu mais cedo, agora sem medo.",
  "Uma xícara de algo quente passa de mão em mão.",
  "Alguém se oferece para a primeira vigília da noite.",
  "O silêncio da noite é interrompido por um bocejo alto.",
  "Alguém pergunta se vale a pena continuar amanhã.",
  "O grupo concorda que sim, claro que sim.",
  "Uma velha lenda é recontada, com alguns detalhes a mais.",
  "Alguém dorme sentado, apoiado na própria mochila.",
  "O fogo diminui aos poucos, e ninguém se importa.",
  "Alguém observa as chamas sem dizer nada por um tempo.",
  "O grupo compara cicatrizes, algumas mais exageradas que outras.",
  "Uma última rodada de água é distribuída antes de dormir.",
  "Alguém insiste em ficar de vigia, mesmo exausto.",
  "O silêncio da noite parece, hoje, gentil.",
  "Alguém pergunta que horas são, sem realmente querer saber.",
  "O grupo se deita, um a um, perto do fogo.",
  "Uma risada solitária escapa antes do sono chegar.",
  "Alguém murmura algo dormindo, e ninguém pergunta o quê.",
  "O fogo ainda ilumina os rostos cansados do grupo.",
  "Alguém finalmente relaxa os ombros, tensos o dia todo.",
  "O grupo compartilha o pouco que ainda resta da comida.",
  "Uma conversa boba sobre o futuro surge do nada.",
  "Alguém aponta que amanhã será um dia mais longo.",
  "O grupo prefere não pensar nisso agora.",
  "Uma coruja canta ao longe, e ninguém se assusta mais.",
  "Alguém ajeita a fogueira antes que ela apague de vez.",
  "O calor ainda resiste, mesmo com o fogo baixo.",
  "Alguém sussurra boa noite, sem esperar resposta.",
  "O grupo adormece aos poucos, um som de respiração por vez.",
  "Uma última brasa ainda brilha na escuridão.",
  "Alguém acorda no meio da noite, olha ao redor, e volta a dormir.",
  "O silêncio da madrugada é quebrado só pelo vento.",
  "Alguém sonha alto, e ninguém comenta de manhã.",
  "O grupo acorda aos poucos, com o corpo dolorido.",
  "Uma última xícara é aquecida nas brasas que sobraram.",
  "Alguém espreguiça, reclamando do chão duro.",
  "O grupo se prepara, devagar, para seguir em frente.",
  "Uma piada da noite anterior ainda arranca sorrisos.",
  "Alguém apaga o que restou da fogueira com cuidado.",
  "O grupo verifica se esqueceu algo no acampamento.",
  "Uma última olhada para o lugar onde dormiram.",
  "Alguém agradece, baixinho, por mais uma noite tranquila.",
  "O grupo se levanta, um pouco mais leve do que ontem.",
  "Uma sensação de que já valeu a pena parar, mesmo que só por uma noite.",
  "Alguém guarda a última lembrança da noite antes de seguir.",
  "O grupo faz as pazes com o cansaço, só por hoje.",
  "Uma última brincadeira antes de voltar à estrada.",
  "Alguém verifica se todos dormiram bem, à sua maneira.",
  "O grupo se levanta, pronto para o que vier a seguir.",
];

const RETURNING_NARRATIVES: string[] = [
  "A estrada parece menor na volta.",
  "As mochilas voltam mais pesadas.",
  "Alguns voltam sorrindo.",
  "Outros apenas voltam.",
  "O grupo caminha mais devagar do que na ida.",
  "Alguém conta uma história do que aconteceu, já exagerando um pouco.",
  "O silêncio da volta é diferente do silêncio da ida.",
  "Alguém carrega um companheiro cansado pelo braço.",
  "O caminho de volta parece mais familiar.",
  "Uma música baixa é assobiada por alguém.",
  "O grupo reconhece marcos que passaram na ida.",
  "Alguém já pensa no que vai comer ao chegar.",
  "O cansaço aparece nos ombros de todos.",
  "Alguém ri de algo que só faz sentido para o grupo.",
  "O caminho de volta parece mais curto do que realmente é.",
  "Alguém conta os passos que faltam, sem motivo.",
  "O grupo caminha em silêncio por um bom trecho.",
  "Uma bota machuca mais na volta do que na ida.",
  "Alguém aponta a Capital ao longe, aliviado.",
  "O peso das mochilas incomoda mais a cada passo.",
  "Alguém pergunta se valeu a pena.",
  "O grupo concorda que sim, mesmo cansado.",
  "Uma piada antiga é repetida, e ainda funciona.",
  "Alguém caminha mancando, discretamente.",
  "O sol começa a baixar enquanto o grupo avança.",
  "Alguém sonha acordado com uma cama de verdade.",
  "O caminho de volta parece mais tranquilo, por hora.",
  "Alguém conta as histórias que vai contar ao chegar.",
  "O grupo já discute onde vão comer primeiro.",
  "Uma última pausa antes da reta final.",
  "Alguém aponta um marco conhecido no caminho.",
  "O grupo apressa o passo, sentindo o fim próximo.",
  "Uma conversa boba anima os últimos passos.",
  "Alguém já sente o cheiro da Capital, ou acha que sente.",
  "O caminho de volta parece nunca terminar, mas termina.",
  "Alguém troca de ombro a mochila, mais uma vez.",
  "O grupo caminha em fila, cansado mas inteiro.",
  "Uma risada quebra o silêncio da estrada vazia.",
  "Alguém pergunta a que horas devem chegar.",
  "O grupo não sabe, e segue mesmo assim.",
  "Uma última colina separa o grupo da Capital.",
  "Alguém acelera o passo, ansioso para chegar.",
  "O grupo avista os portões ao longe, finalmente.",
  "Uma sensação de alívio toma conta de todos.",
  "Alguém sorri, mesmo sem energia para mais nada.",
  "O grupo se aproxima devagar dos portões da Capital.",
  "Uma última conversa sobre o que fazer ao chegar.",
  "Alguém já pensa em tirar as botas assim que possível.",
  "O barulho da cidade volta a ser ouvido ao longe.",
  "O grupo atravessa os portões, finalmente.",
  "Alguém acena para quem os espera.",
  "O cansaço parece menor agora que chegaram.",
  "Alguém já promete contar tudo direitinho, mais tarde.",
  "O grupo se separa aos poucos, cada um para seu canto.",
  "Uma última risada é compartilhada antes de se despedirem.",
  "Alguém agradece o grupo, baixinho, antes de ir embora.",
  "O silêncio da Capital à noite parece estranhamente calmo.",
  "Alguém já sente falta da estrada, só um pouco.",
  "O grupo promete se encontrar de novo em breve.",
  "Uma última mochila é descarregada, com alívio.",
  "Alguém finalmente troca de roupa, aliviado.",
  "O cheiro de casa é diferente de tudo que viram lá fora.",
  "Alguém guarda as coisas com cuidado, já pensando na próxima vez.",
  "O grupo descansa, cada um à sua maneira, já em casa.",
  "Uma sensação estranha de que a estrada ainda os espera.",
  "Alguém dorme assim que se deita, sem nem perceber.",
  "O grupo se separa, mas o assunto vai render por dias.",
  "Alguém sorri sozinho, lembrando de um momento da viagem.",
  "A Capital parece igual, mas algo mudou, um pouco.",
  "O grupo já sabe: vai ter uma próxima vez.",
];

const NARRATIVES_BY_STATUS: Record<ExpeditionStatus, string[]> = {
  preparing: PREPARING_NARRATIVES,
  exploring: EXPLORING_NARRATIVES,
  combating: COMBATING_NARRATIVES,
  resting: RESTING_NARRATIVES,
  returning: RETURNING_NARRATIVES,
  completed: [],
};

// Sorteada a cada chamada (cada poll/render já existente de Character/
// Overlay/Portão Norte) — de propósito, não memoizada: é o "flicker"
// ambiente que dá a sensação de que a aventura continua acontecendo
// mesmo com a aba parada, complementar ao Encounter (que é estável por
// visita ao estado).
export function pickExpeditionNarrative(status: ExpeditionStatus): string | null {
  const pool = NARRATIVES_BY_STATUS[status];
  if (!pool || pool.length === 0) return null;
  return pool[Math.floor(Math.random() * pool.length)];
}
