// Sprint Tavern Stories (MVP) — catálogos estáticos da Taverna. Puro
// conteúdo/apresentação: nenhuma mecânica, nenhuma persistência, nenhum
// dado vindo do backend. Humor de vida cotidiana (Constituição do
// Mundo) — nunca paródia, nunca meme de internet.

// "Rumor do Dia" — uma única história por visita, sorteada no cliente.
// Nada aqui precisa ser verdade: são rumores.
export const TAVERN_RUMORS: string[] = [
  "Disseram que um aventureiro voltou vivo das Ruínas Esquecidas.",
  "O Ferreiro jurou que alguém tentou afiar uma colher.",
  "Ninguém sabe quem continua roubando as maçãs da praça.",
  "O Guarda diz que ouviu passos na muralha durante a madrugada.",
  "Dizem que a Bibliotecária dorme lá dentro há três dias.",
  "Um viajante jura ter visto luzes no Pântano Podre à noite.",
  "Alguém trocou o sino da torre por um mais desafinado. Ninguém confessa.",
  "O poço da Vila do Bosque continua sem fundo, dizem os mais teimosos.",
  "Um cavalo apareceu na praça sem dono. Ninguém reclamou o cavalo.",
  "Contam que um explorador voltou de Picos Congelados falando só em rimas.",
  "O Tesoureiro jura que contou o mesmo Gold duas vezes essa semana.",
  "Uma criança jura ter visto um dragão. Era uma nuvem grande.",
  "Alguém deixou uma carta sem assinatura na Guilda. Ninguém a leu até o fim.",
  "Dizem que o Deserto de Vidro engoliu mais uma bota essa semana.",
  "Um mercador afirma ter vendido a mesma espada três vezes para o mesmo homem.",
  "Ouviram cantoria vindo da Fortaleza Sombria. Ninguém foi conferir.",
  "Um aventureiro trocou seu escudo por um chapéu. Ninguém entendeu por quê.",
  "Dizem que o Ferreiro fala sozinho enquanto forja. Ele nega.",

  // Sprint Wolves Ecosystem (Phase I) — 15 rumores sobre os Lobos do
  // Bosque Sussurrante e variantes regionais.
  "Borin jura que um lobo já roeu o cabo de um martelo esquecido do lado de fora da forja.",
  "Dizem que a matilha do Bosque Sussurrante cresceu — ninguém sabe contar quantos são de verdade.",
  "Um caçador voltou sem uma bota e sem explicação. Só disse 'foi um lobo' e não quis falar mais.",
  "Greta guarda uma presa de lobo debaixo do balcão. Ninguém sabe desde quando, nem por quê.",
  "Idris jura ter visto o mesmo lobo em duas regiões diferentes, no mesmo dia.",
  "Contam que o Lobo Alfa só aparece pra quem já enfrentou a matilha inteira e sobreviveu.",
  "Um fazendeiro das Colinas Áridas culpa os lobos por todo galinheiro vazio, mesmo quando a raposa é mais provável.",
  "Yannick tem um caderno só de rastros de lobo, catalogados por tamanho da pegada.",
  "Dizem que um filhote de lobo foi visto sozinho perto da Capital. Ninguém teve coragem de se aproximar.",
  "Um viajante afirma que os lobos do Pântano Podre nadam melhor do que caçam.",
  "Contam que existe um lobo nos Picos Congelados com presas que brilham como gelo puro.",
  "Borin recusa forjar armadilhas pra lobo. Diz que não é esse tipo de ferreiro.",
  "Uma criança jura ter dado comida pra um lobo e ele simplesmente foi embora, sem atacar.",
  "Dizem que existe um lobo tão velho que já foi visto pela avó de quem conta a história agora.",
  "Alguém ouviu uivos vindos de três direções diferentes na mesma noite, no Bosque Sussurrante.",
];

// "Mesa dos Aventureiros" — pelo menos 30 diálogos curtos, todos
// diferentes, todos reutilizáveis. Cada entrada é uma pequena conversa
// (2 a 4 falas).
export const TAVERN_CONVERSATIONS: string[][] = [
  ["Aquele lobo parecia menor quando eu contei a história.", "Foi o lobo que ficou maior."],
  [
    "Quem foi o maluco que enfrentou um Boss usando Luvas Rasgadas?",
    "Ele venceu.",
    "Mentira.",
    "As luvas perderam.",
  ],
  ["Você viu o tamanho daquela aranha nas Minas Abandonadas?", "Vi o tamanho da sua cara quando ela pulou."],
  ["Eu não corri.", "Você derrubou a mesa correndo.", "Foi estratégia.", "Estratégia de correr."],
  ["Troquei minha espada por uma faca de cozinha.", "E funcionou?", "Melhor que a espada, sinceramente."],
  ["Alguém viu meu escudo?", "Vi ele virar prato ontem à noite.", "Isso explica o cheiro de sopa."],
  ["Dormi na Planície Dourada e sonhei que era rei.", "De quê?", "Da planície.", "Isso já é seu mesmo."],
  ["O Guarda me deixou passar sem perguntar nada.", "Ele te reconheceu.", "Ou desistiu de perguntar."],
  ["Encontrei uma moeda estranha no Litoral Quebrado.", "Gasta ela?", "Não sei de onde é.", "Gasta assim mesmo."],
  ["Três dias no Bosque Sussurrante e só ouvi passarinho.", "Passarinho grande?", "Não sei, eu corri."],
  ["Meu personagem subiu de nível ontem.", "Sentiu diferença?", "Sim.", "Qual?", "Fome."],
  ["Vi um sujeito treinando sozinho na Arena de madrugada.", "Kade?", "De novo."],
  [
    "Perdi uma aposta e agora devo uma rodada pro grupo inteiro.",
    "Aposta de quê?",
    "Se o lobo era grande ou gigante.",
    "E era?",
    "Gigante. Eu sabia.",
  ],
  [
    "Achei um chapéu chique na trilha.",
    "Onde?",
    "Numa trilha que não leva a lugar nenhum.",
    "E você seguiu ela mesmo assim?",
    "O chapéu era bonito.",
  ],
  ["Ouvi dizer que tem gente estudando os lobos.", "Pra quê?", "Pra entender por que fogem de mim.", "Talvez seja o cheiro."],
  ["Voltei da Fortaleza Sombria inteiro.", "Só inteiro?", "E com menos coragem que antes."],
  ["Aposto que aquele Boss nem viu a gente chegando.", "Viu, sim.", "Como você sabe?", "Porque ele riu."],
  ["Minha armadura range toda vez que eu ando.", "Isso é normal?", "Não sei, mas assusta os lobos."],
  ["Achei estranho o poço não ter fundo.", "Você jogou uma pedra?", "Joguei três.", "E?", "Ainda não ouvi nenhuma."],
  ["Aquele Boss quase me pegou.", "Quase não conta.", "Conta pra mim."],
  ["Vou tentar de novo amanhã.", "Tentar o quê?", "Não sei, mas vou tentar."],
  ["Alguém trocou meu elmo por um chapéu de festa.", "Foi você mesmo, ontem, bêbado.", "Isso explica muita coisa."],
  ["O ferreiro cobrou caro dessa vez.", "Ele sempre cobra caro.", "Dessa vez foi mais caro que caro."],
  ["Você acredita em Grandes Feras?", "Acredito em conta grande de taverna.", "Isso é mais assustador."],
  ["Vi uma sombra enorme no Deserto de Vidro.", "Era o quê?", "Minha própria sombra.", "Ah."],
  ["Fiquei sabendo que alguém desafiou o Mestre da Arena.", "E?", "Ainda estamos esperando notícias."],
  ["Troquei de região três vezes hoje.", "Por quê?", "Procurando alguém que não fugisse de mim."],
  ["Aquele item que eu achei era mágico?", "Era uma pedra.", "Uma pedra especial?", "Uma pedra."],
  [
    "Ouvi um barulho estranho vindo do Pântano Podre.",
    "Foi você que fez.",
    "Como você sabe?",
    "Porque só você reclama de barulho estranho toda noite.",
  ],
  ["Achei que ia ser fácil.", "Nada nesse Reino é fácil.", "Devia ter uma placa avisando isso na entrada."],
];

// "Recados na Parede" — cerca de 50 bilhetes, misturando humor,
// seriedade e coisas estranhas.
export const TAVERN_WALL_NOTES: string[] = [
  "Perdi uma panela.",
  "Se encontrar um chapéu, ele provavelmente é meu.",
  "Procura-se alguém que saiba cozinhar.",
  "NÃO alimentar os patos.",
  "Vendo botas quase novas. Uma delas fura um pouco.",
  "Compro histórias de viagem. Pago em pão.",
  "Se você pegou minha corda emprestada, devolva. Se não pegou, ainda assim procure uma corda.",
  "Aula de escrita aos domingos. Tragam a própria pena.",
  "Achado: um anel. Achado: outro anel. Achado: sim, os dois eram meus.",
  "Alguém sabe consertar um relógio? Um específico, na torre.",
  "Ofereço abrigo por uma noite em troca de uma boa história.",
  "Não deixem a porta dos fundos aberta. Os gansos entram.",
  "Vendo espada. Nunca usada. Comprada por engano.",
  "Se você é o dono da cabra, ela está na minha horta de novo.",
  "Preciso de alguém forte para carregar barris. Sem perguntas.",
  "Perdido: senso de direção. Última vez visto nas Colinas Áridas.",
  "Troco remendos de roupa por informações sobre o Litoral Quebrado.",
  "Aviso: o poço não é um desejo. É só um poço.",
  "Alguém emprestou meu machado há dois anos. Ainda espero.",
  "Vendo mapa antigo. Provavelmente errado.",
  "Recompensa para quem encontrar meu gato. Ele não quer ser encontrado, mas tente.",
  "Aula de dança improvisada essa noite, quem quiser aparecer.",
  "Aviso da Guarda: não escalar a muralha. De novo.",
  "Alguém está deixando flores na porta da ferraria. O Ferreiro quer saber quem.",
  "Compro qualquer coisa que brilhe. Não pergunto de onde veio.",
  "Se essa carta é sua, sinto muito. Se não é, ignore.",
  "Aviso: a fonte da praça não serve pra lavar roupa.",
  "Alguém viu um cachorro com uma bota na boca? A bota é minha. O cachorro não.",
  "Vendo remédio para ressaca. Funciona às vezes.",
  "Precisa-se de testemunha. Não vou dizer para quê.",
  "Achei uma chave. Não abre nenhuma porta que eu conheço.",
  "Aula de costura cancelada essa semana. A professora sumiu.",
  "Aviso: não cutucar o poço com um graveto. Alguém sempre cutuca.",
  "Vendo três galinhas. Uma delas é especial. Não direi qual.",
  "Se alguém souber cantar bem, a Taverna está contratando. Ou só ouvindo.",
  "Perdido: um par de luvas rasgadas. Não que valham muito, mas eram minhas.",
  "Aviso: o sino da torre está desafinado. Ninguém sabe desde quando.",
  "Procuro companhia para viagem. Prefiro alguém que não fale demais.",
  "Vendo lanterna que às vezes acende sozinha. Talvez seja um defeito.",
  "Aula de esgrima básica aos sábados. Tragam um pedaço de madeira.",
  "Se você é dono do porco que está solto na praça, venha buscá-lo antes que ele vire jantar.",
  "Recompensa para quem contar uma história que eu ainda não ouvi.",
  "Aviso: as maçãs da praça não são de graça. Alguém continua achando que são.",
  "Vendo uma armadura. Só um pouco amassada. Tem história.",
  "Preciso de alguém que saiba ler mapas velhos. Muito velhos.",
  "Achado: uma carta de amor. Não é minha, mas é bonita.",
  "Aviso: não durma perto da lareira. Alguém sempre dorme perto da lareira.",
  "Vendo semente rara. Talvez cresça. Talvez não. Aceito o risco quem comprar.",
  "Aula de contar histórias aos domingos. Requisito: ter pelo menos uma.",
  "Se alguém encontrar minha coragem, devolva na Taverna.",
];

// "Música da Noite" — só os títulos, nunca tocada. Cerca de 40, entre
// engraçados e melancólicos.
export const TAVERN_NIGHT_SONGS: string[] = [
  "O Último Barril",
  "Canção da Ponte Velha",
  "O Ferreiro Apaixonado",
  "Dança do Lobo",
  "Cerveja Antes da Glória",
  "A Balada do Aventureiro Cansado",
  "Três Moedas e um Adeus",
  "O Sino que Não Toca Certo",
  "Lamento das Colinas Áridas",
  "A Garota do Litoral Quebrado",
  "Onde Foi Meu Cavalo",
  "Noite Sem Estrelas",
  "O Brinde dos Que Ficaram",
  "Canção do Poço Sem Fundo",
  "Valsa da Última Rodada",
  "O Explorador Que Nunca Voltou",
  "Cinco Copos de Coragem",
  "A Dança da Fogueira",
  "Lá Vem o Vento do Deserto de Vidro",
  "Balada do Escudo Perdido",
  "O Homem Que Cantava Sozinho",
  "Canção Para Ninguém Ouvir",
  "A Última Vela da Taverna",
  "O Grito da Fortaleza",
  "Serenata Para uma Cabra",
  "O Peso da Armadura Velha",
  "Refrão do Aventureiro Bêbado",
  "A Ponte Que Ninguém Atravessa",
  "Canção do Primeiro Amanhecer",
  "O Fim de Uma Longa Estrada",
  "Balada das Luvas Rasgadas",
  "A Taverna Nunca Dorme",
  "Canto Baixo Para Noites Longas",
  "O Último Suspiro do Herói",
  "Dança Torta do Ferreiro",
  "Melodia da Praça Vazia",
  "A Canção Que Ninguém Termina",
  "Barril Vazio, Copo Cheio",
  "O Segredo do Bosque Sussurrante",
  "Última Canção Antes do Silêncio",
];
