// Sprint Tavern Stories (MVP) — catálogos estáticos da Taverna. Puro
// conteúdo/apresentação: nenhuma mecânica, nenhuma persistência, nenhum
// dado vindo do backend. Humor de vida cotidiana (Constituição do
// Mundo) — nunca paródia, nunca meme de internet.

// "Rumor do Dia" — uma única história por visita, sorteada no cliente.
// Nada aqui precisa ser verdade: são rumores.
export const TAVERN_RUMORS: string[] = [
  "Disseram que um aventureiro voltou vivo das Ruínas Esquecidas.",
  "O Ferreiro jurou que alguém tentou afiar uma colher.",
  "Ninguém sabe quem continua roubando as maçãs da praça.",
  "O Guarda diz que ouviu passos na muralha durante a madrugada.",
  "Dizem que a Bibliotecária dorme lá dentro há três dias.",
  "Um viajante jura ter visto luzes no Pântano Podre à noite.",
  "Alguém trocou o sino da torre por um mais desafinado. Ninguém confessa.",
  "O poço da Vila do Bosque continua sem fundo, dizem os mais teimosos.",
  "Um cavalo apareceu na praça sem dono. Ninguém reclamou o cavalo.",
  "Contam que um explorador voltou de Picos Congelados falando só em rimas.",
  "O Tesoureiro jura que contou o mesmo Gold duas vezes essa semana.",
  "Uma criança jura ter visto um dragão. Era uma nuvem grande.",
  "Alguém deixou uma carta sem assinatura na Guilda. Ninguém a leu até o fim.",
  "Dizem que o Deserto de Vidro engoliu mais uma bota essa semana.",
  "Um mercador afirma ter vendido a mesma espada três vezes para o mesmo homem.",
  "Ouviram cantoria vindo da Fortaleza Sombria. Ninguém foi conferir.",
  "Um aventureiro trocou seu escudo por um chapéu. Ninguém entendeu por quê.",
  "Dizem que o Ferreiro fala sozinho enquanto forja. Ele nega.",

  // Sprint Wolves Ecosystem (Phase I) — 15 rumores sobre os Lobos do
  // Bosque Sussurrante e variantes regionais.
  "Borin jura que um lobo já roeu o cabo de um martelo esquecido do lado de fora da forja.",
  "Dizem que a matilha do Bosque Sussurrante cresceu — ninguém sabe contar quantos são de verdade.",
  "Um caçador voltou sem uma bota e sem explicação. Só disse 'foi um lobo' e não quis falar mais.",
  "Greta guarda uma presa de lobo debaixo do balcão. Ninguém sabe desde quando, nem por quê.",
  "Idris jura ter visto o mesmo lobo em duas regiões diferentes, no mesmo dia.",
  "Contam que o Lobo Alfa só aparece pra quem já enfrentou a matilha inteira e sobreviveu.",
  "Um fazendeiro das Colinas Áridas culpa os lobos por todo galinheiro vazio, mesmo quando a raposa é mais provável.",
  "Yannick tem um caderno só de rastros de lobo, catalogados por tamanho da pegada.",
  "Dizem que um filhote de lobo foi visto sozinho perto da Capital. Ninguém teve coragem de se aproximar.",
  "Um viajante afirma que os lobos do Pântano Podre nadam melhor do que caçam.",
  "Contam que existe um lobo nos Picos Congelados com presas que brilham como gelo puro.",
  "Borin recusa forjar armadilhas pra lobo. Diz que não é esse tipo de ferreiro.",
  "Uma criança jura ter dado comida pra um lobo e ele simplesmente foi embora, sem atacar.",
  "Dizem que existe um lobo tão velho que já foi visto pela avó de quem conta a história agora.",
  "Alguém ouviu uivos vindos de três direções diferentes na mesma noite, no Bosque Sussurrante.",

  // Sprint Ravens Ecosystem (Phase I) — 15 rumores sobre os Corvos do
  // Reino.
  "Dizem que os corvos sabem quando alguém vai morrer antes de acontecer. Ninguém confirma.",
  "Um viajante jura que um corvo o seguiu por três dias inteiros, sem motivo aparente.",
  "Contam que centenas de corvos levantaram voo ao mesmo tempo nas Ruínas Esquecidas, sem ninguém saber por quê.",
  "Miriam garante que um corvo pousou na janela da Biblioteca e ficou ali a tarde inteira.",
  "Dizem que existe um corvo tão velho que já foi visto observando o mesmo aventureiro por anos.",
  "Idris afirma que já confiou uma mensagem a um corvo. Só uma vez. Nunca mais repetiu.",
  "Um caçador jura que os corvos sempre sabem onde a matilha de lobos caçou, antes de qualquer humano perceber.",
  "Greta diz que um corvo entra na Taverna toda noite de chuva e só vai embora de madrugada.",
  "Borin jura que um corvo já roubou um prego da bigorna, na frente dele, sem pressa nenhuma.",
  "Dizem que ver um corvo sozinho é sinal de boa sorte. Ver muitos juntos, ninguém sabe dizer.",
  "Um explorador dos Picos Congelados jura que um bando de corvos o seguiu até o topo, sem nunca pousar.",
  "Yannick tem um caderno inteiro só sobre o comportamento dos corvos. Ainda incompleto.",
  "Contam que um corvo pousou sobre uma lápide vazia nas Ruínas Esquecidas e ficou ali dias.",
  "Alguém jura ter visto um corvo observar uma expedição inteira, do início ao fim, sem nunca se aproximar.",
  "Dizem que os corvos entendem tudo que os humanos falam. Ninguém consegue provar.",

  // Sprint Ancient Ruins Ecosystem (Phase I) — 20 rumores sobre as
  // Ruínas Antigas, sempre contraditórios entre si.
  "Dizem que as Ruínas Esquecidas são mais antigas que o próprio Reino. Meu avô jurava o contrário.",
  "Alguns dizem que ninguém nunca voltou de dentro da Câmara das Vozes. Outros dizem que voltam sempre, só não lembram.",
  "Ninguém entra na Torre Sem Entrada. Não porque seja proibido — porque ninguém encontra a porta.",
  "Dizem que a Estátua Sem Rosto já teve rosto, sim. Alguém jura o contrário.",
  "Meu avô jurava que via luzes na Arena Afundada, à noite. Meu pai nunca viu nada.",
  "Alguns dizem que os símbolos do penhasco mudam sozinhos. Outros dizem que é só a luz enganando.",
  "Dizem que o Poço Seco nunca teve água. Um velho pescador jura o contrário, sem explicar como sabia.",
  "Ninguém sabe quem fez o Portal de Pedra da Fronteira. Todo mundo tem uma teoria diferente, e nenhuma prova.",
  "Dizem que a Máscara Enterrada do Pântano está afundando, devagar, há anos. Outros dizem que está exatamente na mesma posição desde sempre.",
  "Alguns dizem que o Vestígio do Acampamento Antigo foi abandonado às pressas. Outros dizem que foi abandonado com calma, tudo arrumado.",
  "Meu avô jurava que essas Ruínas foram feitas por gente como a gente. Um estudioso da Capital discorda, sem dizer por quê.",
  "Dizem que essas Ruínas não pertencem a nenhum povo conhecido. Ninguém confirma, ninguém nega.",
  "Ninguém entra na Escadaria que Termina na Pedra achando que é só uma parede. Alguns dizem que já ouviram passos do outro lado.",
  "Alguns dizem que as Ruínas têm mais de mil anos. Outros dizem que ninguém tem como saber isso.",
  "Dizem que existe uma décima terceira ruína, ainda não encontrada. Ninguém confirma a contagem oficial.",
  "Meu avô jurava ter visto alguém saindo de dentro da Estátua Sem Rosto. Ninguém mais na família acredita nele.",
  "Alguns dizem que as Ruínas foram feitas por magia. Outros dizem que magia não tinha nada a ver com aquilo.",
  "Dizem que quem entra na Câmara das Vozes ouve a própria voz responder primeiro. Ninguém confirma isso de perto.",
  "Ninguém sabe se as Ruínas foram abandonadas ou se ainda têm alguém morando lá dentro.",
  "Alguns dizem que os corvos evitam pousar perto de certas Ruínas. Outros dizem que é exatamente o contrário.",

  // Sprint Kingdom Folk (Phase I) — 40 rumores sobre moradores comuns
  // do Reino, nunca sobre heróis.
  "Dizem que o lenhador novo derruba árvore mais rápido que qualquer um da vila. Outros dizem que ele só chegou primeiro nas mais fáceis.",
  "Um carvoeiro jura que não dorme há três dias vigiando o forno. A esposa dele jura que ele dormiu, sim, e roncou a noite inteira.",
  "Contam que a pescadora do Litoral Quebrado devolve todo peixe grande demais. Alguém jura que ela só não consegue puxar os maiores.",
  "Dizem que o oleiro novo já quebrou cem potes aprendendo o ofício. Ele mesmo diz que foram só uns vinte.",
  "Meu avô jurava que a pastora das Colinas reconhece cada ovelha pelo nome. Minha avó dizia que ela só finge.",
  "Alguns dizem que o pedreiro velho constrói parede mais forte que qualquer um. Outros dizem que ele só usa mais pedra que o necessário.",
  "Dizem que a mensageira nunca se perdeu em vinte anos de estrada. Ninguém confirma, porque ninguém andou com ela o tempo todo.",
  "Um ferreiro itinerante consertou a vila inteira de graça, dizem. Outros dizem que ele só queria a companhia, não a bondade.",
  "Meu avô jurava que a curandeira nunca errou um diagnóstico. Meu pai lembra de pelo menos duas vezes que ela errou feio.",
  "Dizem que o caçador novo poupa filhote de qualquer animal. Alguns acham isso nobre. Outros acham que ele só tem pontaria ruim.",
  "Ninguém sabe explicar como a mineira sente o veio acabar antes de qualquer instrumento. Alguns dizem que é sorte, não talento.",
  "Dizem que o apicultor nunca leva picada. Um vizinho jura que já viu ele inchado feito um sapo, mês passado.",
  "Alguns dizem que o fabricante de cordas trança mais rápido de noite. Outros dizem que ele só erra menos quando está sozinho.",
  "Dizem que o fabricante de barris nunca vendeu um que vazasse. A cervejeira da vila discorda, e tem prova guardada em casa.",
  "Meu avô jurava que o lavrador reza pra chuva na mesma data todo ano. Meu pai diz que é só coincidência de estação.",
  "Dizem que o barqueiro atravessa o rio de olhos fechados. Ninguém nunca teve coragem de pedir pra ele provar.",
  "Alguns dizem que o moleiro parou o próprio moinho por um pássaro preso na engrenagem. Outros dizem que foi só um defeito comum.",
  "Dizem que a tecelã reproduz qualquer padrão de memória. Uma cliente jura que ela errou o dela, semana passada.",
  "Meu avô jurava que o tintureiro nunca repete a mesma cor duas vezes de propósito. Outros dizem que ele simplesmente não consegue.",
  "Dizem que o curtidor não sente mais o próprio cheiro. A esposa dele garante que sente, sim, e reclama todo santo dia.",
  "Alguns dizem que a sapateira reconhece o dono de um sapato só pelo desgaste. Outros dizem que ela só decora os clientes de tanto vê-los.",
  "Dizem que o alfaiate não usa fita métrica há anos. Um cliente jura que a roupa dele ficou torta mês passado, sim.",
  "Meu avô jurava que a padeira acorda a vila inteira com o cheiro do pão. Minha avó dizia que era o galo, não o pão.",
  "Dizem que o cervejeiro guarda o barril que estragou só de lembrança. Outros dizem que ele só não teve coragem de jogar fora.",
  "Alguns dizem que a vinicultora guarda um barril há doze anos esperando o ano perfeito. Outros acham que ela só esqueceu dele lá.",
  "Dizem que o queijeiro reconhece o rebanho só pelo sabor do queijo. Um cliente garante que ele errou da última vez.",
  "Meu avô jurava que a açougueira não desperdiça nada do animal. Outros dizem que ela só é econômica demais, e chamam de outro nome.",
  "Dizem que o carpinteiro só errou a medida uma vez na vida. A vizinhança discorda, e lembra de outras casas tortas.",
  "Alguns dizem que a marceneira guarda o primeiro móvel torto que fez. Outros dizem que ela só não teve coragem de queimar.",
  "Dizem que o vidreiro soprou, uma vez, a garrafa perfeita. Ninguém mais viu essa garrafa depois daquele dia.",
  "Meu avô jurava que a cesteira trança de olhos fechados. Minha avó dizia que ela só decorou o movimento de tanto repetir.",
  "Dizem que o ceramista perdeu uma fornada inteira por causa do vento. Outros dizem que ele só errou a temperatura mesmo.",
  "Alguns dizem que o cordoalheiro testa a corda com o próprio peso. Outros dizem que ele só gosta de se pendurar nela sem motivo.",
  "Dizem que o estivador carregou um piano inteiro sozinho. Um colega jura que eram quatro pessoas ajudando, não uma.",
  "Meu avô jurava que a salineira perdeu três tanques numa única tempestade. Outros dizem que foi só um tanque, exagerado com o tempo.",
  "Dizem que o carroceiro conhece atalho que nem mapa nenhum mostra. Ninguém nunca conseguiu seguir ele até esses lugares.",
  "Alguns dizem que a ferradora nunca encontrou cavalo nervoso demais. Outros dizem que ela só evita os mais difíceis.",
  "Dizem que a criadora de cavalos dá nome a cada potro, mesmo os vendidos rápido. Um comprador jura que ela chorou na despedida de um deles.",
  "Meu avô jurava que o tosquiador é o mais rápido do Reino. Outros dizem que ele só tosquia mal, e por isso é rápido.",
  "Dizem que a coletora de ervas anda no escuro reconhecendo tudo pelo cheiro. Ninguém nunca a acompanhou pra confirmar.",

  // Sprint First WOW Moment (Phase I) — 2 rumores sobre as Luvas
  // Rasgadas, o equipamento inicial de todo aventureiro novo.
  "Dizem que um aventureiro novo apareceu com luvas tão rasgadas que nem os fios seguravam mais nada. Ainda assim, seguiu em frente.",
  "Contam que alguém tentou consertar as próprias luvas rasgadas com um fio de pescar. Não funcionou. Virou piada da Taverna até hoje.",

  // Sprint StreamRPG Identity (Phase I) — pequenas menções aos
  // símbolos do Reino, espalhadas pelo mesmo rumor do dia de sempre.
  "Dizem que o primeiro corvo estudado no Reino era um Corvo-de-Ferro que roubava moeda da Talia. Ainda rouba, segundo ela.",
  "Ninguém sabe o que tem dentro do barril da praça. Alguém já chutou, já bateu, já perguntou. O barril continua vazio, ou continua guardando segredo.",
  "Dizem que quem lava as mãos na fonte da praça sai com sorte. As Luvas Rasgadas de alguém continuaram sujas mesmo assim.",
  "Contam que a Primeira Ponte nunca precisou de reparo de verdade. Alguns acham isso um milagre. Outros acham que ninguém teve coragem de checar direito.",

  // Sprint StreamRPG Identity (Phase II) — segunda leva de símbolos.
  "Dizem que o poço da Vila do Bosque não tem fundo mesmo. Alguém já jogou uma pedra há anos. Ninguém ouviu ela bater em lugar nenhum ainda.",
  "Contam que o Sino da Torre já tocou sozinho, sem vento e sem mão nenhuma por perto. Duas vezes, dizem os mais velhos. Ninguém concorda no resto dos detalhes.",
  "Dizem que ninguém que entra na Fortaleza Sombria sai exatamente do mesmo jeito que entrou. Ninguém explica o que muda.",
  "Contam que a Quebra do Primeiro Reino começou com uma discussão pequena, numa mesa de taverna parecida com essa. Ninguém sabe dizer sobre o quê.",

  // Sprint Place Identity (Phase I)
  "Dizem que a árvore da praça já foi maior ainda, antes de um raio atingir um galho, décadas atrás. Ainda cresce, devagar, como se não tivesse pressa nenhuma.",
  "Contam que a Torre do Portão Norte range à noite, mesmo sem vento nenhum. Os guardas mais antigos dizem que sempre foi assim, desde que se lembram.",

  // Sprint Cross References & Narrative Cohesion (Phase I)
  "Um pastor da Planície Dourada jura que a Coluna Partida já foi cercada de pedras, faz muito tempo. Ninguém mais viu essas pedras, nem os filhos dele.",
  "Um velho das Colinas Áridas jura ter visto o muro inteiro em volta do Portão, décadas atrás. Ninguém da idade dele lembra do mesmo jeito.",
];

// "Mesa dos Aventureiros" — pelo menos 30 diálogos curtos, todos
// diferentes, todos reutilizáveis. Cada entrada é uma pequena conversa
// (2 a 4 falas).
export const TAVERN_CONVERSATIONS: string[][] = [
  ["Aquele lobo parecia menor quando eu contei a história.", "Foi o lobo que ficou maior."],
  [
    "Quem foi o maluco que enfrentou um Boss usando Luvas Rasgadas?",
    "Ele venceu.",
    "Mentira.",
    "As luvas perderam.",
  ],
  ["Você viu o tamanho daquela aranha nas Minas Abandonadas?", "Vi o tamanho da sua cara quando ela pulou."],
  ["Eu não corri.", "Você derrubou a mesa correndo.", "Foi estratégia.", "Estratégia de correr."],
  ["Troquei minha espada por uma faca de cozinha.", "E funcionou?", "Melhor que a espada, sinceramente."],
  ["Alguém viu meu escudo?", "Vi ele virar prato ontem à noite.", "Isso explica o cheiro de sopa."],
  ["Dormi na Planície Dourada e sonhei que era rei.", "De quê?", "Da planície.", "Isso já é seu mesmo."],
  ["O Guarda me deixou passar sem perguntar nada.", "Ele te reconheceu.", "Ou desistiu de perguntar."],
  ["Encontrei uma moeda estranha no Litoral Quebrado.", "Gasta ela?", "Não sei de onde é.", "Gasta assim mesmo."],
  ["Três dias no Bosque Sussurrante e só ouvi passarinho.", "Passarinho grande?", "Não sei, eu corri."],
  ["Meu personagem subiu de nível ontem.", "Sentiu diferença?", "Sim.", "Qual?", "Fome."],
  ["Vi um sujeito treinando sozinho na Arena de madrugada.", "Kade?", "De novo."],
  [
    "Perdi uma aposta e agora devo uma rodada pro grupo inteiro.",
    "Aposta de quê?",
    "Se o lobo era grande ou gigante.",
    "E era?",
    "Gigante. Eu sabia.",
  ],
  [
    "Achei um chapéu chique na trilha.",
    "Onde?",
    "Numa trilha que não leva a lugar nenhum.",
    "E você seguiu ela mesmo assim?",
    "O chapéu era bonito.",
  ],
  ["Ouvi dizer que tem gente estudando os lobos.", "Pra quê?", "Pra entender por que fogem de mim.", "Talvez seja o cheiro."],
  ["Voltei da Fortaleza Sombria inteiro.", "Só inteiro?", "E com menos coragem que antes."],
  ["Aposto que aquele Boss nem viu a gente chegando.", "Viu, sim.", "Como você sabe?", "Porque ele riu."],
  ["Minha armadura range toda vez que eu ando.", "Isso é normal?", "Não sei, mas assusta os lobos."],
  ["Achei estranho o poço não ter fundo.", "Você jogou uma pedra?", "Joguei três.", "E?", "Ainda não ouvi nenhuma."],
  ["Aquele Boss quase me pegou.", "Quase não conta.", "Conta pra mim."],
  ["Vou tentar de novo amanhã.", "Tentar o quê?", "Não sei, mas vou tentar."],
  ["Alguém trocou meu elmo por um chapéu de festa.", "Foi você mesmo, ontem, bêbado.", "Isso explica muita coisa."],
  ["O ferreiro cobrou caro dessa vez.", "Ele sempre cobra caro.", "Dessa vez foi mais caro que caro."],
  ["Você acredita em Grandes Feras?", "Acredito em conta grande de taverna.", "Isso é mais assustador."],
  ["Vi uma sombra enorme no Deserto de Vidro.", "Era o quê?", "Minha própria sombra.", "Ah."],
  ["Fiquei sabendo que alguém desafiou o Mestre da Arena.", "E?", "Ainda estamos esperando notícias."],
  ["Troquei de região três vezes hoje.", "Por quê?", "Procurando alguém que não fugisse de mim."],
  ["Aquele item que eu achei era mágico?", "Era uma pedra.", "Uma pedra especial?", "Uma pedra."],
  [
    "Ouvi um barulho estranho vindo do Pântano Podre.",
    "Foi você que fez.",
    "Como você sabe?",
    "Porque só você reclama de barulho estranho toda noite.",
  ],
  ["Achei que ia ser fácil.", "Nada nesse Reino é fácil.", "Devia ter uma placa avisando isso na entrada."],
];

// "Recados na Parede" — cerca de 50 bilhetes, misturando humor,
// seriedade e coisas estranhas.
export const TAVERN_WALL_NOTES: string[] = [
  "Perdi uma panela.",
  "Se encontrar um chapéu, ele provavelmente é meu.",
  "Procura-se alguém que saiba cozinhar.",
  "NÃO alimentar os patos.",
  "Vendo botas quase novas. Uma delas fura um pouco.",
  "Compro histórias de viagem. Pago em pão.",
  "Se você pegou minha corda emprestada, devolva. Se não pegou, ainda assim procure uma corda.",
  "Aula de escrita aos domingos. Tragam a própria pena.",
  "Achado: um anel. Achado: outro anel. Achado: sim, os dois eram meus.",
  "Alguém sabe consertar um relógio? Um específico, na torre.",
  "Ofereço abrigo por uma noite em troca de uma boa história.",
  "Não deixem a porta dos fundos aberta. Os gansos entram.",
  "Vendo espada. Nunca usada. Comprada por engano.",
  "Se você é o dono da cabra, ela está na minha horta de novo.",
  "Preciso de alguém forte para carregar barris. Sem perguntas.",
  "Perdido: senso de direção. Última vez visto nas Colinas Áridas.",
  "Troco remendos de roupa por informações sobre o Litoral Quebrado.",
  "Aviso: o poço não é um desejo. É só um poço.",
  "Alguém emprestou meu machado há dois anos. Ainda espero.",
  "Vendo mapa antigo. Provavelmente errado.",
  "Recompensa para quem encontrar meu gato. Ele não quer ser encontrado, mas tente.",
  "Aula de dança improvisada essa noite, quem quiser aparecer.",
  "Aviso da Guarda: não escalar a muralha. De novo.",
  "Alguém está deixando flores na porta da ferraria. O Ferreiro quer saber quem.",
  "Compro qualquer coisa que brilhe. Não pergunto de onde veio.",
  "Se essa carta é sua, sinto muito. Se não é, ignore.",
  "Aviso: a fonte da praça não serve pra lavar roupa.",
  "Alguém viu um cachorro com uma bota na boca? A bota é minha. O cachorro não.",
  "Vendo remédio para ressaca. Funciona às vezes.",
  "Precisa-se de testemunha. Não vou dizer para quê.",
  "Achei uma chave. Não abre nenhuma porta que eu conheço.",
  "Aula de costura cancelada essa semana. A professora sumiu.",
  "Aviso: não cutucar o poço com um graveto. Alguém sempre cutuca.",
  "Vendo três galinhas. Uma delas é especial. Não direi qual.",
  "Se alguém souber cantar bem, a Taverna está contratando. Ou só ouvindo.",
  "Perdido: um par de luvas rasgadas. Não que valham muito, mas eram minhas.",
  "Aviso: o sino da torre está desafinado. Ninguém sabe desde quando.",
  "Procuro companhia para viagem. Prefiro alguém que não fale demais.",
  "Vendo lanterna que às vezes acende sozinha. Talvez seja um defeito.",
  "Aula de esgrima básica aos sábados. Tragam um pedaço de madeira.",
  "Se você é dono do porco que está solto na praça, venha buscá-lo antes que ele vire jantar.",
  "Recompensa para quem contar uma história que eu ainda não ouvi.",
  "Aviso: as maçãs da praça não são de graça. Alguém continua achando que são.",
  "Vendo uma armadura. Só um pouco amassada. Tem história.",
  "Preciso de alguém que saiba ler mapas velhos. Muito velhos.",
  "Achado: uma carta de amor. Não é minha, mas é bonita.",
  "Aviso: não durma perto da lareira. Alguém sempre dorme perto da lareira.",
  "Vendo semente rara. Talvez cresça. Talvez não. Aceito o risco quem comprar.",
  "Aula de contar histórias aos domingos. Requisito: ter pelo menos uma.",
  "Se alguém encontrar minha coragem, devolva na Taverna.",
];

// "Música da Noite" — só os títulos, nunca tocada. Cerca de 40, entre
// engraçados e melancólicos.
export const TAVERN_NIGHT_SONGS: string[] = [
  "O Último Barril",
  "Canção da Ponte Velha",
  "O Ferreiro Apaixonado",
  "Dança do Lobo",
  "Cerveja Antes da Glória",
  "A Balada do Aventureiro Cansado",
  "Três Moedas e um Adeus",
  "O Sino que Não Toca Certo",
  "Lamento das Colinas Áridas",
  "A Garota do Litoral Quebrado",
  "Onde Foi Meu Cavalo",
  "Noite Sem Estrelas",
  "O Brinde dos Que Ficaram",
  "Canção do Poço Sem Fundo",
  "Valsa da Última Rodada",
  "O Explorador Que Nunca Voltou",
  "Cinco Copos de Coragem",
  "A Dança da Fogueira",
  "Lá Vem o Vento do Deserto de Vidro",
  "Balada do Escudo Perdido",
  "O Homem Que Cantava Sozinho",
  "Canção Para Ninguém Ouvir",
  "A Última Vela da Taverna",
  "O Grito da Fortaleza",
  "Serenata Para uma Cabra",
  "O Peso da Armadura Velha",
  "Refrão do Aventureiro Bêbado",
  "A Ponte Que Ninguém Atravessa",
  "Canção do Primeiro Amanhecer",
  "O Fim de Uma Longa Estrada",
  "Balada das Luvas Rasgadas",
  "A Taverna Nunca Dorme",
  "Canto Baixo Para Noites Longas",
  "O Último Suspiro do Herói",
  "Dança Torta do Ferreiro",
  "Melodia da Praça Vazia",
  "A Canção Que Ninguém Termina",
  "Barril Vazio, Copo Cheio",
  "O Segredo do Bosque Sussurrante",
  "Última Canção Antes do Silêncio",
];
